#!/usr/bin/env python3
"""Extract TrinityCore relation predicates verbatim into generated headers (Track B).

Same idea as ``tools/tc_pet_probe``: the C++ side of the differential is Trinity's
own text, compiled against minimal stubs (probe.cpp).

Extracted verbatim (TrinityCore @ 7f3d43b):
  SharedDefines.h   enum ReputationRank, SpellAttr0, SpellAttr5, SpellAttr6, SpellAttr8, SpellAttr11
  UnitDefines.h     enum UnitPVPStateFlags, UnitFlags, UnitFlags2
  Unit.h            enum UnitState
  Player.h          enum DuelState, PlayerFlags
  DBCEnums.h        enum FactionTemplateFlags, FactionMasks, enum class SummonPropertiesFlags
  ReputationMgr.h   enum class ReputationFlags
  SpellInfo.h       enum SpellCustomAttributes
  DB2Structure.h    FactionEntry::CanHaveReputation, FactionTemplateEntry (helpers)
  Object.cpp        WorldObject::GetCharmerOrOwner, GetCharmerOrOwnerOrSelf, GetCharmerOrOwnerPlayerOrPlayerItself,
                    GetAffectingPlayer, GetReactionTo, GetFactionReactionTo, IsHostileTo, IsFriendlyTo,
                    IsValidAttackTarget, IsValidAssistTarget
  Unit.cpp          Unit::IsInPartyWith, Unit::IsInRaidWith
  Player.cpp        Player::IsInSameGroupWith, Player::IsInSameRaidWith
  ReputationMgr.cpp ReputationMgr::GetState(FactionEntry const*), IsAtWar(FactionEntry const*),
                    GetForcedRankIfAny (both overloads)

Cut points (stubbed in probe.cpp): object storage / ObjectAccessor (a table of fat
objects), CanSeeOrDetect (a per-pair table), faction stores, reputation lists,
group membership (group id + subgroup), SpellInfo (stated IsPositive /
IsAffectingArea / IsAllowingDeadTarget / attribute words), vehicles (never set),
ReputationMgr::GetRank (stated rank).
"""

from __future__ import annotations

import sys
from pathlib import Path

WORKSPACE_PARENT = Path(__file__).resolve().parents[5]
TC_ROOT = Path(sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] else WORKSPACE_PARENT / "TrinityCore")
OUT_DIR = Path(sys.argv[2] if len(sys.argv) > 2 else Path(__file__).parent)
OUT_DECLS = OUT_DIR / "tc_relation_decls.inc"
OUT_BODIES = OUT_DIR / "tc_relation_bodies.inc"
G = TC_ROOT / "src/server/game"


def read(rel: str) -> str:
    return (G / rel).read_text(encoding="utf-8")


def braced(text: str, start: int) -> tuple[int, int]:
    open_brace = text.index("{", start)
    depth = 0
    for pos in range(open_brace, len(text)):
        if text[pos] == "{":
            depth += 1
        elif text[pos] == "}":
            depth -= 1
            if depth == 0:
                return open_brace, pos + 1
    raise SystemExit("unbalanced braces")


def unique(text: str, needle: str, source: str) -> int:
    start = text.find(needle)
    if start < 0:
        raise SystemExit(f"not found in {source}: {needle}")
    if text.find(needle, start + 1) >= 0:
        raise SystemExit(f"not unique in {source}: {needle}")
    return start


def enum_block(text: str, header: str, source: str) -> str:
    start = unique(text, header + "\n", source)
    _, end = braced(text, start)
    line = text.count("\n", 0, start) + 1
    return f"// {source}:{line}\n{text[start:end]};"


def function(text: str, signature: str, source: str) -> str:
    start = unique(text, signature, source)
    line = text.count("\n", 0, start) + 1
    _, b = braced(text, start)
    return f"// {source}:{line}\n{text[start:b]}\n"


def main() -> int:
    shared = read("Miscellaneous/SharedDefines.h")
    unitdefs = read("Entities/Unit/UnitDefines.h")
    unit_h = read("Entities/Unit/Unit.h")
    player_h = read("Entities/Player/Player.h")
    dbc = read("DataStores/DBCEnums.h")
    repmgr_h = read("Reputation/ReputationMgr.h")
    spellinfo_h = read("Spells/SpellInfo.h")
    db2s = read("DataStores/DB2Structure.h")
    obj = read("Entities/Object/Object.cpp")
    unit = read("Entities/Unit/Unit.cpp")
    player = read("Entities/Player/Player.cpp")
    repmgr = read("Reputation/ReputationMgr.cpp")

    decls = ["// GENERATED by tools/tc_target_relation_probe/extract.py from TrinityCore -- do not edit"]
    for text, header, src in (
            (shared, "enum ReputationRank", "SharedDefines.h"),
            (shared, "enum SpellAttr0 : uint32", "SharedDefines.h"),
            (shared, "enum SpellAttr5 : uint32", "SharedDefines.h"),
            (shared, "enum SpellAttr6 : uint32", "SharedDefines.h"),
            (shared, "enum SpellAttr8 : uint32", "SharedDefines.h"),
            (shared, "enum SpellAttr11 : uint32", "SharedDefines.h"),
            (unitdefs, "enum UnitPVPStateFlags : uint8", "UnitDefines.h"),
            (unitdefs, "enum UnitFlags : uint32", "UnitDefines.h"),
            (unitdefs, "enum UnitFlags2 : uint32", "UnitDefines.h"),
            (unit_h, "enum UnitState : uint32", "Unit.h"),
            (player_h, "enum DuelState", "Player.h"),
            (player_h, "enum PlayerFlags", "Player.h"),
            (dbc, "enum FactionTemplateFlags", "DBCEnums.h"),
            (dbc, "enum FactionMasks", "DBCEnums.h"),
            (dbc, "enum class SummonPropertiesFlags : uint32", "DBCEnums.h"),
            (repmgr_h, "enum class ReputationFlags : uint16", "ReputationMgr.h"),
            (spellinfo_h, "enum SpellCustomAttributes", "SpellInfo.h")):
        decls.append(enum_block(text, header, src))
    decls.append("DEFINE_ENUM_FLAG(SummonPropertiesFlags);\nDEFINE_ENUM_FLAG(ReputationFlags);")
    # FactionEntry::CanHaveReputation + FactionTemplateEntry helpers (member bodies, verbatim)
    s = unique(db2s, "    bool CanHaveReputation() const", "DB2Structure.h")
    _, e = braced(db2s, s)
    decls.append("// DB2Structure.h:%d\nstruct FactionEntry\n{\n    uint32 ID;\n    int16 ReputationIndex;\n%s\n};"
                 % (db2s.count("\n", 0, s) + 1, db2s[s:e]))
    s = unique(db2s, "struct FactionTemplateEntry\n", "DB2Structure.h")
    _, e = braced(db2s, s)
    decls.append(f"// DB2Structure.h:{db2s.count(chr(10), 0, s) + 1}\n{db2s[s:e]};")

    bodies = ["// GENERATED by tools/tc_target_relation_probe/extract.py from TrinityCore -- do not edit"]
    for sig in ("Unit* WorldObject::GetCharmerOrOwner() const",
                "Unit* WorldObject::GetCharmerOrOwnerOrSelf() const",
                "Player* WorldObject::GetCharmerOrOwnerPlayerOrPlayerItself() const",
                "Player* WorldObject::GetAffectingPlayer() const",
                "ReputationRank WorldObject::GetReactionTo(WorldObject const* target) const",
                "/*static*/ ReputationRank WorldObject::GetFactionReactionTo(FactionTemplateEntry const* factionTemplateEntry, WorldObject const* target)",
                "bool WorldObject::IsHostileTo(WorldObject const* target) const",
                "bool WorldObject::IsFriendlyTo(WorldObject const* target) const",
                "bool WorldObject::IsValidAttackTarget(WorldObject const* target, SpellInfo const* bySpell /*= nullptr*/) const",
                "bool WorldObject::IsValidAssistTarget(WorldObject const* target, SpellInfo const* bySpell /*= nullptr*/) const"):
        bodies.append(function(obj, sig, "Object.cpp"))
    for sig in ("bool Unit::IsInPartyWith(Unit const* unit) const", "bool Unit::IsInRaidWith(Unit const* unit) const"):
        bodies.append(function(unit, sig, "Unit.cpp"))
    for sig in ("bool Player::IsInSameGroupWith(Player const* p) const", "bool Player::IsInSameRaidWith(Player const* p) const"):
        bodies.append(function(player, sig, "Player.cpp"))
    for sig in ("FactionState const* ReputationMgr::GetState(FactionEntry const* factionEntry) const",
                "bool ReputationMgr::IsAtWar(FactionEntry const* factionEntry) const",
                "ReputationRank const* ReputationMgr::GetForcedRankIfAny(FactionTemplateEntry const* factionTemplateEntry) const",
                "ReputationRank const* ReputationMgr::GetForcedRankIfAny(uint32 factionId) const"):
        bodies.append(function(repmgr, sig, "ReputationMgr.cpp"))

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_DECLS.write_text("\n\n".join(decls) + "\n", encoding="utf-8")
    OUT_BODIES.write_text("\n\n".join(bodies) + "\n", encoding="utf-8")
    print(f"wrote {OUT_DECLS.name} ({len(decls)} blocks), {OUT_BODIES.name} ({len(bodies)} blocks) from {TC_ROOT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
