#!/usr/bin/env python3
"""Extract TrinityCore aura-identity code verbatim (aura-lifecycle Track A).

The C++ side of the differential for ``aura_lifecycle/identity.py`` is Trinity's own
text compiled against minimal stubs (``probe.cpp``).

Extracted verbatim (TrinityCore @ 7f3d43b):
  Unit.cpp        Unit::_TryStackingOrRefreshingExistingAura, Unit::GetOwnedAura
  SpellAuras.cpp  Aura::CanStackWith
  SpellInfo.cpp   SpellEffectInfo::IsEffect (x2), IsAura (x2), IsAreaAuraEffect, IsUnitOwnedAuraEffect,
                  SpellInfo::IsPassive, IsStackableOnOneSlotWithDifferentCasters, IsMultiSlotAura,
                  IsChanneled, IsRankOf, IsDifferentRankOf, IsAuraExclusiveBySpecificWith,
                  IsAuraExclusiveBySpecificPerCasterWith, _LoadSpellSpecific
  enums           SpellAttr0..16, SpellFamilyNames, DispelType (SharedDefines.h), AuraType (SpellAuraDefines.h),
                  SpellEffectName values (SharedDefines.h), SpellSpecificType / SpellCustomAttributes (SpellInfo.h),
                  SpellGroupStackRule (SpellMgr.h), SpellEffIndex (SharedDefines.h),
                  SpellAuraInterruptFlags (SpellDefines.h), SpellEffectAttributes (DBCEnums.h)
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

WORKSPACE_PARENT = Path(__file__).resolve().parents[5]
TC_ROOT = Path(sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] else WORKSPACE_PARENT / "TrinityCore")
OUT_DIR = Path(sys.argv[2] if len(sys.argv) > 2 else Path(__file__).parent)
OUT_DECLS = OUT_DIR / "tc_identity_decls.inc"
OUT_BODIES = OUT_DIR / "tc_identity_bodies.inc"
G = TC_ROOT / "src/server/game"


def braced(text: str, start: int) -> tuple[int, int]:
    open_brace = text.index("{", start)
    depth = 0
    for pos in range(open_brace, len(text)):
        if text[pos] == "{":
            depth += 1
        elif text[pos] == "}":
            depth -= 1
            if depth == 0:
                return open_brace, pos + 1
    raise SystemExit("unbalanced braces")


def function(text: str, signature: str, source: str) -> str:
    start = text.find(signature)
    if start < 0:
        raise SystemExit(f"signature not found in {source}: {signature}")
    if text.find(signature, start + 1) >= 0:
        raise SystemExit(f"signature not unique in {source}: {signature}")
    line = text.count("\n", 0, start) + 1
    _, b = braced(text, start)
    return f"// {source}:{line}\n{text[start:b]}\n"


def enum_block(text: str, head: str, source: str) -> str:
    start = text.index(head)
    end = text.index("};", start) + 2
    line = text.count("\n", 0, start) + 1
    return f"// {source}:{line}\n{text[start:end]}"


def main() -> int:
    unit_cpp = (G / "Entities/Unit/Unit.cpp").read_text(encoding="utf-8")
    auras_cpp = (G / "Spells/Auras/SpellAuras.cpp").read_text(encoding="utf-8")
    info_cpp = (G / "Spells/SpellInfo.cpp").read_text(encoding="utf-8")
    info_h = (G / "Spells/SpellInfo.h").read_text(encoding="utf-8")
    shared = (G / "Miscellaneous/SharedDefines.h").read_text(encoding="utf-8")
    aura_defs = (G / "Spells/Auras/SpellAuraDefines.h").read_text(encoding="utf-8")
    mgr_h = (G / "Spells/SpellMgr.h").read_text(encoding="utf-8")
    defines_h = (G / "Spells/SpellDefines.h").read_text(encoding="utf-8")
    dbc_enums = (G / "DataStores/DBCEnums.h").read_text(encoding="utf-8")

    effects = re.findall(r"^\s*(SPELL_EFFECT_[A-Z0-9_]+)\s*=\s*(\d+),", shared, re.MULTILINE)
    effect_enum = "// SharedDefines.h SpellEffectName (values)\nenum SpellEffects : uint32\n{\n" + \
        "\n".join(f"    {n} = {v}," for n, v in effects) + "\n};"
    decls = ["// GENERATED by tools/tc_aura_identity_probe/extract.py from TrinityCore -- do not edit", effect_enum]
    for w in range(17):
        decls.append(enum_block(shared, f"enum SpellAttr{w} : uint32", "SharedDefines.h"))
    decls += [
        enum_block(shared, "enum SpellFamilyNames : uint8", "SharedDefines.h"),
        enum_block(shared, "enum DispelType", "SharedDefines.h"),
        enum_block(aura_defs, "enum AuraType : uint32", "SpellAuraDefines.h"),
        enum_block(info_h, "enum SpellSpecificType", "SpellInfo.h"),
        enum_block(info_h, "enum SpellCustomAttributes", "SpellInfo.h"),
        enum_block(mgr_h, "enum SpellGroupStackRule", "SpellMgr.h"),
        enum_block(shared, "enum SpellEffIndex : uint8", "SharedDefines.h"),
        enum_block(defines_h, "enum class SpellAuraInterruptFlags : uint32", "SpellDefines.h"),
        enum_block(dbc_enums, "enum class SpellEffectAttributes", "DBCEnums.h"),
    ]
    bodies = ["// GENERATED by tools/tc_aura_identity_probe/extract.py from TrinityCore -- do not edit"]
    for sig in ("bool SpellEffectInfo::IsEffect() const",
                "bool SpellEffectInfo::IsEffect(SpellEffects effectName) const",
                "bool SpellEffectInfo::IsAura() const",
                "bool SpellEffectInfo::IsAura(AuraType aura) const",
                "bool SpellEffectInfo::IsAreaAuraEffect() const",
                "bool SpellEffectInfo::IsUnitOwnedAuraEffect() const",
                "bool SpellInfo::IsPassive() const",
                "bool SpellInfo::IsMultiSlotAura() const",
                "bool SpellInfo::IsStackableOnOneSlotWithDifferentCasters() const",
                "bool SpellInfo::IsChanneled() const",
                "bool SpellInfo::IsAuraExclusiveBySpecificWith(SpellInfo const* spellInfo) const",
                "bool SpellInfo::IsAuraExclusiveBySpecificPerCasterWith(SpellInfo const* spellInfo) const",
                "void SpellInfo::_LoadSpellSpecific()",
                "bool SpellInfo::IsRankOf(SpellInfo const* spellInfo) const",
                "bool SpellInfo::IsDifferentRankOf(SpellInfo const* spellInfo) const"):
        bodies.append(function(info_cpp, sig, "SpellInfo.cpp"))
    bodies.append(function(auras_cpp, "bool Aura::CanStackWith(Aura const* existingAura) const", "SpellAuras.cpp"))
    for sig in ("Aura* Unit::_TryStackingOrRefreshingExistingAura(AuraCreateInfo& createInfo)",
                "Aura* Unit::GetOwnedAura(uint32 spellId, ObjectGuid casterGUID, ObjectGuid itemCasterGUID, uint32 reqEffMask, Aura* except) const"):
        bodies.append(function(unit_cpp, sig, "Unit.cpp"))

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_DECLS.write_text("\n\n".join(decls) + "\n", encoding="utf-8")
    OUT_BODIES.write_text("\n\n".join(bodies) + "\n", encoding="utf-8")
    print(f"wrote {OUT_DECLS.name} ({len(decls)} blocks), {OUT_BODIES.name} ({len(bodies)} blocks) from {TC_ROOT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
