#!/usr/bin/env python3
"""Extract TrinityCore code verbatim for the R2 (snapshot/timing) hostile-review probe.

Reuses the Track D extractor (``tools/tc_aura_periodic_probe/extract.py``) for the periodic core
(AuraEffect::Update/GetTotalTicks/CalculatePeriodic/ResetPeriodic, Aura::UpdateOwner/Update/SetDuration/
RefreshDuration/RefreshTimers/ModStackAmount, the Spell.cpp duration commit, the _UpdateSpells loops) and adds
the refresh / duration-mutation entry points the pass did not model, each verbatim:

  SpellAuras.h:135        AuraCreateInfo::ResetPeriodicTimer default (used by Unit::AddAura, steal, vehicle paths)
  SpellEffects.cpp:6138   Spell::EffectModifyAuraStacks MiscValue 0 statement (SPELL_EFFECT_MODIFY_AURA_STACKS 289)
  SpellAuraEffects.cpp    AuraEffect::HandleAuraLinked REAPPLY statement (ModStackAmount(diff))
  spell_priest.cpp        spell_pri_painful_punishment (390686) SetDuration-only extension
                          spell_pri_mental_decay (375994) SetMaxDuration(remaining+x) + SetDuration extension
"""

from __future__ import annotations

import importlib.util
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
spec = importlib.util.spec_from_file_location("tcd_extract", HERE.parent / "tc_aura_periodic_probe" / "extract.py")
tcd = importlib.util.module_from_spec(spec)
spec.loader.exec_module(tcd)

WORKSPACE_PARENT = Path(__file__).resolve().parents[5]
TC_ROOT = Path(sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] else WORKSPACE_PARENT / "TrinityCore")
OUT_DIR = Path(sys.argv[2] if len(sys.argv) > 2 else HERE)
G = TC_ROOT / "src/server/game"
S = TC_ROOT / "src/server/scripts"


def line_of(text: str, needle: str, source: str) -> tuple[int, str]:
    start = tcd.unique(text, needle, source)
    return text.count("\n", 0, start) + 1, needle


def main() -> int:
    # 1. the Track D verbatim core, into our own directory
    tcd.TC_ROOT = TC_ROOT
    tcd.G = G
    tcd.OUT_DIR = OUT_DIR
    tcd.OUT_DECLS = OUT_DIR / "tc_r2_decls.inc"
    tcd.OUT_BODIES = OUT_DIR / "tc_r2_bodies.inc"
    rc = tcd.main()
    if rc:
        return rc

    auras_h = (G / "Spells/Auras/SpellAuras.h").read_text(encoding="utf-8")
    effects_cpp = (G / "Spells/SpellEffects.cpp").read_text(encoding="utf-8")
    aeff_cpp = (G / "Spells/Auras/SpellAuraEffects.cpp").read_text(encoding="utf-8")
    priest = (S / "Spells/spell_priest.cpp").read_text(encoding="utf-8")

    out = ["// GENERATED by tools/tc_aura_r2_probe/extract.py from TrinityCore -- do not edit"]
    ln, txt = line_of(auras_h, "    bool ResetPeriodicTimer = true;", "SpellAuras.h")
    m = re.match(r"\s*bool ResetPeriodicTimer = (true|false);", txt)
    out.append(f"// SpellAuras.h:{ln}\nconstexpr bool AuraCreateInfoDefaultResetPeriodicTimer = {m.group(1)};\n")

    ln, txt = line_of(effects_cpp, "            targetAura->ModStackAmount(GetEffectValueAsInt());", "SpellEffects.cpp")
    out.append(f"// SpellEffects.cpp:{ln} (Spell::EffectModifyAuraStacks, MiscValue 0)\n"
               "void ProbeEffectModifyAuraStacks(Aura* targetAura, int32 value)\n{\n"
               "    auto GetEffectValueAsInt = [value]() { return value; };\n" + txt + "\n}\n")

    ln, txt = line_of(aeff_cpp, "            triggeredAura->ModStackAmount(GetBase()->GetStackAmount() - triggeredAura->GetStackAmount());",
                      "SpellAuraEffects.cpp")
    out.append(f"// SpellAuraEffects.cpp:{ln} (AuraEffect::HandleAuraLinked, REAPPLY)\n"
               "void ProbeAuraLinkedReapply(Aura* triggeredAura, Aura* parent)\n{\n"
               "    auto GetBase = [parent]() { return parent; };\n" + txt + "\n}\n")

    ln, txt = line_of(priest, "            shadowWordPain->SetDuration(shadowWordPain->GetDuration() + additionalDuration);", "spell_priest.cpp")
    out.append(f"// spell_priest.cpp:{ln} (spell_pri_painful_punishment)\n"
               "void ProbePainfulPunishment(Aura* shadowWordPain, int32 additionalDuration)\n{\n" + txt + "\n}\n")

    a = tcd.unique(priest, "            shadowWordPain->SetMaxDuration(shadowWordPain->GetDuration() + durationExtend);", "spell_priest.cpp")
    b = priest.index("        }", a)
    ln = priest.count("\n", 0, a) + 1
    out.append(f"// spell_priest.cpp:{ln} (spell_pri_mental_decay)\n"
               "void ProbeMentalDecay(Aura* shadowWordPain, int32 durationExtend)\n{\n" + priest[a:b] + "}\n")

    (OUT_DIR / "tc_r2_extra.inc").write_text("\n".join(out) + "\n", encoding="utf-8")
    print("wrote tc_r2_extra.inc")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
