#!/usr/bin/env python3
"""Extract TrinityCore load-time positivity code verbatim into generated headers.

Same pattern as ``tools/tc_target_selector_probe``: Trinity's own text compiled against
minimal stubs (``probe.cpp``).

Extracted verbatim (TrinityCore @ 7f3d43b):
  SharedDefines.h        enum SpellEffIndex, SpellAttr0, SpellAttr1, SpellAttr4, SpellEffects,
                         Mechanics, DispelType, SpellFamilyNames
  SpellAuraDefines.h     enum AuraType
  SpellDefines.h         enum class SpellModOp
  DBCEnums.h             enum class SpellEffectAttributes + DEFINE_ENUM_FLAG
  SpellInfo.h            enum SpellTargetCheckTypes
  SpellInfo.cpp          SpellEffectInfo::{IsEffect, IsAura, IsAreaAuraEffect, IsUnitOwnedAuraEffect},
                         SpellInfo::{IsPassive, IsPositive, IsPositiveEffect},
                         _isPositiveTarget, _isPositiveEffectImpl, SpellInfo::_InitializeSpellPositivity

Cut points (stubbed in probe.cpp): ``SpellImplicitTargetInfo`` returns the driver's target id and
check type; ``SpellEffectInfo::CalcValue()`` returns the driver's load-time value (the Python
``positivity.Loader.calc_value``); ``sSpellMgr->GetSpellInfo(id, difficulty)`` looks the id up in the
driver's spell set; the load order of ``LoadSpellInfoCustomAttributes`` (SpellMgr.cpp:3031, a boost
hashed container) is the driver's ``O`` line.
"""

from __future__ import annotations

import sys
from pathlib import Path

WORKSPACE_PARENT = Path(__file__).resolve().parents[5]
TC_ROOT = Path(sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] else WORKSPACE_PARENT / "TrinityCore")
OUT_DIR = Path(sys.argv[2] if len(sys.argv) > 2 else Path(__file__).parent)
G = TC_ROOT / "src/server/game"


def read(rel: str) -> str:
    return (G / rel).read_text(encoding="utf-8")


def line_of(text: str, pos: int) -> int:
    return text.count("\n", 0, pos) + 1


def braced(text: str, start: int) -> tuple[int, int]:
    open_brace = text.index("{", start)
    depth = 0
    for pos in range(open_brace, len(text)):
        if text[pos] == "{":
            depth += 1
        elif text[pos] == "}":
            depth -= 1
            if depth == 0:
                return open_brace, pos + 1
    raise SystemExit("unbalanced braces")


def unique(text: str, needle: str, source: str) -> int:
    start = text.find(needle)
    if start < 0:
        raise SystemExit(f"not found in {source}: {needle}")
    if text.find(needle, start + 1) >= 0:
        raise SystemExit(f"not unique in {source}: {needle}")
    return start


def block(text: str, header: str, source: str) -> str:
    start = unique(text, header, source)
    _, end = braced(text, start)
    return f"// {source}:{line_of(text, start)}\n{text[start:end]};\n"


def function(text: str, signature: str, source: str) -> str:
    start = unique(text, signature, source)
    _, b = braced(text, start)
    return f"// {source}:{line_of(text, start)}\n{text[start:b]}\n"


def main() -> int:
    shared = read("Miscellaneous/SharedDefines.h")
    auras = read("Spells/Auras/SpellAuraDefines.h")
    spelldefs = read("Spells/SpellDefines.h")
    dbc = read("DataStores/DBCEnums.h")
    info_h = read("Spells/SpellInfo.h")
    info = read("Spells/SpellInfo.cpp")
    decls = ["// GENERATED by tools/tc_target_positivity_probe/extract.py from TrinityCore -- do not edit"]
    for header in ("enum SpellEffIndex : uint8", "enum SpellAttr0 : uint32", "enum SpellAttr1 : uint32",
                   "enum SpellAttr4 : uint32", "\nenum SpellEffects\n", "enum Mechanics : uint32",
                   "\nenum DispelType\n", "enum SpellFamilyNames : uint8"):
        decls.append(block(shared, header, "SharedDefines.h"))
    decls.append(block(auras, "enum AuraType : uint32", "SpellAuraDefines.h"))
    decls.append(block(spelldefs, "enum class SpellModOp : uint8", "SpellDefines.h"))
    decls.append(block(dbc, "enum class SpellEffectAttributes\n", "DBCEnums.h"))
    decls.append("DEFINE_ENUM_FLAG(SpellEffectAttributes);")
    decls.append(block(info_h, "enum SpellTargetCheckTypes : uint8", "SpellInfo.h"))
    bodies = ["// GENERATED by tools/tc_target_positivity_probe/extract.py from TrinityCore -- do not edit"]
    for sig in ("bool SpellEffectInfo::IsEffect() const\n",
                "bool SpellEffectInfo::IsAura() const\n",
                "bool SpellEffectInfo::IsAreaAuraEffect() const\n",
                "bool SpellEffectInfo::IsUnitOwnedAuraEffect() const\n",
                "bool SpellInfo::IsPassive() const\n",
                "bool SpellInfo::IsPositive() const\n",
                "bool SpellInfo::IsPositiveEffect(uint8 effIndex) const\n",
                "inline bool _isPositiveTarget(SpellEffectInfo const& effect)\n",
                "bool _isPositiveEffectImpl(SpellInfo const* spellInfo, SpellEffectInfo const& effect, ",
                "void SpellInfo::_InitializeSpellPositivity()\n"):
        bodies.append(function(info, sig, "SpellInfo.cpp"))
    (OUT_DIR / "tc_positivity_decls.inc").write_text("\n".join(decls) + "\n", encoding="utf-8")
    (OUT_DIR / "tc_positivity_bodies.inc").write_text("\n".join(bodies) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
