#!/usr/bin/env python3
"""Extract TrinityCore AreaTrigger shape-search code verbatim (targeting Track I).

Same pattern as ``tools/tc_target_geom_probe``: the C++ side of the
``targeting/areatriggers.py`` differential is Trinity's own text compiled
against minimal stubs (``probe.cpp``).

Included directly: ``Entities/Object/Position.h``, ``G3D/g3dmath.h``.

Extracted verbatim (TrinityCore @ 7f3d43b):
  AreaTriggerTemplate.h    #define MAX_AREATRIGGER_ENTITY_DATA, struct AreaTriggerShapeInfo
  AreaTriggerTemplate.cpp  AreaTriggerShapeInfo::*::GetMaxSearchRadius (6) + dispatcher
  GridDefines.h            #define MAX_NUMBER_OF_GRIDS, SIZE_OF_GRIDS, MAP_SIZE
  Position.cpp             Position::NormalizeOrientation (linked by Position.h), IsWithinBox, IsInPolygon2D
  Object.cpp               WorldObject::_IsWithinDist, WorldObject::IsWithinDist
  GridNotifiers.h          Trinity::AnyUnitInObjectRangeCheck
  AreaTrigger.cpp          AreaTrigger::SearchUnitInSphere / Box / Polygon / Cylinder / Disk /
                           BoundedPlane, AreaTrigger::GetMaxSearchRadius,
                           AreaTrigger::UpdatePolygonVertices

Cut points (stubbed in probe.cpp): UpdateField wrappers (plain values), CalcCurrentScale /
GetProgress (driver values), DB2 curves (MorphCurveId is 0 in every probe request),
SearchUnits (driver candidate list -> verbatim AnyUnitInObjectRangeCheck; grid visit,
phase and IsStaticSpawn are out of scope), Trinity::Containers::EraseIf (std::erase_if),
transports (none).
"""

from __future__ import annotations

import sys
from pathlib import Path

WORKSPACE_PARENT = Path(__file__).resolve().parents[5]
TC_ROOT = Path(sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] else WORKSPACE_PARENT / "TrinityCore")
OUT_DIR = Path(sys.argv[2] if len(sys.argv) > 2 else Path(__file__).parent)
G = TC_ROOT / "src/server/game"


def braced(text: str, start: int) -> tuple[int, int]:
    open_brace = text.index("{", start)
    depth = 0
    for pos in range(open_brace, len(text)):
        if text[pos] == "{":
            depth += 1
        elif text[pos] == "}":
            depth -= 1
            if depth == 0:
                return open_brace, pos + 1
    raise SystemExit("unbalanced braces")


def function(text: str, signature: str, source: str, suffix: str = "") -> str:
    start = text.find(signature)
    if start < 0:
        raise SystemExit(f"signature not found in {source}: {signature}")
    if text.find(signature, start + 1) >= 0:
        raise SystemExit(f"signature not unique in {source}: {signature}")
    line = text.count("\n", 0, start) + 1
    _, b = braced(text, start)
    if suffix:
        b = text.index(suffix, b) + len(suffix)
    return f"// {source}:{line}\n{text[start:b]}\n"


def define(text: str, name: str, source: str) -> str:
    for n, line in enumerate(text.splitlines(), 1):
        if line.startswith(f"#define {name} "):
            return f"// {source}:{n}\n{line}\n"
    raise SystemExit(f"#define {name} not found in {source}")


def read(rel: str) -> str:
    return (G / rel).read_text(encoding="utf-8")


def main() -> None:
    tmpl_h = read("Entities/AreaTrigger/AreaTriggerTemplate.h")
    tmpl_cpp = read("Entities/AreaTrigger/AreaTriggerTemplate.cpp")
    grid = read("Grids/GridDefines.h")
    pos = read("Entities/Object/Position.cpp")
    obj = read("Entities/Object/Object.cpp")
    notif = read("Grids/Notifiers/GridNotifiers.h")
    at = read("Entities/AreaTrigger/AreaTrigger.cpp")

    decls = [
        "// generated by extract.py -- do not edit\n",
        define(tmpl_h, "MAX_AREATRIGGER_ENTITY_DATA", "AreaTriggerTemplate.h"),
        define(grid, "MAX_NUMBER_OF_GRIDS", "GridDefines.h"),
        define(grid, "SIZE_OF_GRIDS", "GridDefines.h"),
        define(grid, "MAP_SIZE", "GridDefines.h"),
        function(tmpl_h, "struct AreaTriggerShapeInfo\n", "AreaTriggerTemplate.h", suffix=";"),
        "namespace Trinity {\n",
        function(notif, "    class AnyUnitInObjectRangeCheck\n", "GridNotifiers.h", suffix=";"),
        "}\n",
    ]
    bodies = ["// generated by extract.py -- do not edit\n"]
    for name in ("Sphere", "Box", "Polygon", "Cylinder", "Disk", "BoundedPlane"):
        bodies.append(function(tmpl_cpp, f"float AreaTriggerShapeInfo::{name}::GetMaxSearchRadius() const", "AreaTriggerTemplate.cpp"))
    bodies.append(function(tmpl_cpp, "float AreaTriggerShapeInfo::GetMaxSearchRadius() const", "AreaTriggerTemplate.cpp"))
    bodies.append(function(pos, "float Position::NormalizeOrientation(float o)", "Position.cpp"))
    bodies.append(function(pos, "bool Position::IsWithinBox(", "Position.cpp"))
    bodies.append(function(pos, "bool Position::IsInPolygon2D(", "Position.cpp"))
    bodies.append(function(obj, "bool WorldObject::_IsWithinDist(", "Object.cpp"))
    bodies.append(function(obj, "bool WorldObject::IsWithinDist(WorldObject const* obj,", "Object.cpp"))
    for fn in ("SearchUnitInSphere", "SearchUnitInBox", "SearchUnitInPolygon", "SearchUnitInCylinder",
               "SearchUnitInDisk", "SearchUnitInBoundedPlane"):
        bodies.append(function(at, f"void AreaTrigger::{fn}(", "AreaTrigger.cpp"))
    bodies.append(function(at, "float AreaTrigger::GetMaxSearchRadius() const", "AreaTrigger.cpp"))
    bodies.append(function(at, "void AreaTrigger::UpdatePolygonVertices()", "AreaTrigger.cpp"))

    (OUT_DIR / "tc_at_decls.inc").write_text("".join(decls), encoding="utf-8")
    (OUT_DIR / "tc_at_bodies.inc").write_text("".join(bodies), encoding="utf-8")


if __name__ == "__main__":
    main()
