#!/usr/bin/env python3
"""Extract TrinityCore Guardian/Pet stat code verbatim into a generated header.

Same idea as ``tools/tc_probe`` / ``tc_proc_probe``: the C++ side of the
differential is Trinity's own text, compiled against minimal stubs.

Extracted verbatim (TrinityCore @ 7f3d43b):
  SharedDefines.h   enum Stats, MAX_STATS, enum Powers, MAX_POWERS_PER_CLASS, enum SpellSchools,
                    enum WeaponAttackType
  Unit.h            enum UnitModifierFlatType, UnitModifierPctType, WeaponDamageRange, UnitMods
  PetDefines.h      enum PetType
  DBCEnums.h        enum class ExpectedStatType
  ObjectMgr.h       struct PetLevelInfo
  Util.h            CalculatePct
  StatSystem.cpp    #define ENTRY_* block, Unit::UpdateAllResistances, Unit::GetCreatePowerValue,
                    Creature::GetCreatePowerValue, Creature::GetPowerIndex, Guardian::UpdateStats,
                    Guardian::UpdateAllStats, Guardian::UpdateResistances, Guardian::UpdateArmor,
                    Guardian::UpdateMaxHealth, Guardian::UpdateMaxPower,
                    Guardian::UpdateAttackPowerAndDamage, Guardian::UpdateDamagePhysical,
                    Guardian::SetBonusDamage
  Pet.cpp           #define PET_XP_FACTOR, Guardian::InitStatsForLevel
  Unit.cpp          Unit::GetTotalStatValue, GetTotalAuraModValue, SetStatFlatModifier,
                    SetStatPctModifier, GetFlatModifierValue, GetPctModifierValue, UpdateUnitMod,
                    GetSpellSchoolByAuraGroup, GetStatByAuraGroup, GetTotalAttackPowerValue,
                    GetWeaponDamageRange, GetBaseAttackTime
  Creature.cpp      Creature::UpdateLevelDependantStats, GetMaxHealthByLevel,
                    GetBaseDamageForLevel, GetBaseArmorForLevel

Cut points (stubbed in probe.cpp, documented there): update-field plumbing
(SetUpdateFieldValue family), SetMaxHealth / SetMaxPower / SetPowerType /
UpdateStatBuffMod side effects, sObjectMgr / sDB2Manager lookups (the driver
supplies the resolved pet_levelstats row, base mana and ExpectedStat values),
Creature::GetHealthMod (Rate.Creature.HP.* = 1), aura / display / XP calls.
The probe is therefore **bounded**: it proves the arithmetic given those inputs.
"""

from __future__ import annotations

import sys
from pathlib import Path

WORKSPACE_PARENT = Path(__file__).resolve().parents[5]
TC_ROOT = Path(sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] else WORKSPACE_PARENT / "TrinityCore")
OUT_DIR = Path(sys.argv[2] if len(sys.argv) > 2 else Path(__file__).parent)
OUT_DECLS = OUT_DIR / "tc_pet_decls.inc"
OUT_BODIES = OUT_DIR / "tc_pet_bodies.inc"
G = TC_ROOT / "src/server/game"


def read(rel: str) -> str:
    return (G / rel).read_text(encoding="utf-8")


def braced(text: str, start: int) -> tuple[int, int]:
    open_brace = text.index("{", start)
    depth = 0
    for pos in range(open_brace, len(text)):
        if text[pos] == "{":
            depth += 1
        elif text[pos] == "}":
            depth -= 1
            if depth == 0:
                return open_brace, pos + 1
    raise SystemExit("unbalanced braces")


def enum_block(text: str, header: str) -> str:
    start = text.index(header)
    _, end = braced(text, start)
    return text[start:end] + ";"


def function(text: str, signature: str, source: str) -> str:
    start = text.find(signature)
    if start < 0:
        raise SystemExit(f"signature not found in {source}: {signature}")
    if text.find(signature, start + 1) >= 0:
        raise SystemExit(f"signature not unique in {source}: {signature}")
    line = text.count("\n", 0, start) + 1
    _, b = braced(text, start)
    return f"// {source}:{line}\n{text[start:b]}\n"


def between(text: str, first: str, last: str) -> str:
    a = text.index(first)
    b = text.index(last, a) + len(last)
    return text[a:b]


def main() -> int:
    shared = read("Miscellaneous/SharedDefines.h")
    unit_h = read("Entities/Unit/Unit.h")
    petdefs = read("Entities/Pet/PetDefines.h")
    dbc = read("DataStores/DBCEnums.h")
    objmgr_h = read("Globals/ObjectMgr.h")
    util = (TC_ROOT / "src/common/Utilities/Util.h").read_text(encoding="utf-8")
    stat = read("Entities/Unit/StatSystem.cpp")
    pet = read("Entities/Pet/Pet.cpp")
    unit = read("Entities/Unit/Unit.cpp")
    creature = read("Entities/Creature/Creature.cpp")

    decls = [
        "// GENERATED by tools/tc_pet_probe/extract.py from TrinityCore -- do not edit",
        enum_block(shared, "enum Stats : uint16"),
        "#define MAX_STATS                        5",
        enum_block(shared, "enum Powers : int8"),
        "#define MAX_POWERS_PER_CLASS            10",
        enum_block(shared, "enum SpellSchools : uint16"),
        enum_block(shared, "enum WeaponAttackType : uint8"),
        enum_block(unit_h, "enum UnitModifierFlatType"),
        enum_block(unit_h, "enum UnitModifierPctType"),
        enum_block(unit_h, "enum WeaponDamageRange"),
        enum_block(unit_h, "enum UnitMods"),
        enum_block(petdefs, "enum PetType : uint8"),
        enum_block(dbc, "enum class ExpectedStatType : uint8"),
        enum_block(objmgr_h, "struct PetLevelInfo"),
        between(util, "template <class T, class U>\ninline T CalculatePct(T base, U pct)", "}"),
    ]
    bodies = [
        "// GENERATED by tools/tc_pet_probe/extract.py from TrinityCore -- do not edit",
        between(stat, "#define ENTRY_IMP", "#define ENTRY_BLOODWORM         28017"),
        "#define PET_XP_FACTOR 0.05f  // Pet.cpp:44 (" + ("verified" if "#define PET_XP_FACTOR 0.05f" in pet else "MISMATCH") + ")",
    ]
    stat_fns = [
        "void Unit::UpdateAllResistances()",
        "int32 Unit::GetCreatePowerValue(Powers power) const",
        "int32 Creature::GetCreatePowerValue(Powers power) const",
        "uint32 Creature::GetPowerIndex(Powers power) const",
        "bool Guardian::UpdateStats(Stats stat)",
        "bool Guardian::UpdateAllStats()",
        "void Guardian::UpdateResistances(uint32 school)",
        "void Guardian::UpdateArmor()",
        "void Guardian::UpdateMaxHealth()",
        "void Guardian::UpdateMaxPower(Powers power)",
        "void Guardian::UpdateAttackPowerAndDamage(bool ranged)",
        "void Guardian::UpdateDamagePhysical(WeaponAttackType attType)",
        "void Guardian::SetBonusDamage(int32 damage)",
    ]
    for sig in stat_fns:
        bodies.append(function(stat, sig, "StatSystem.cpp"))
    bodies.append(function(pet, "bool Guardian::InitStatsForLevel(uint8 petlevel)", "Pet.cpp"))
    unit_fns = [
        "float Unit::GetTotalStatValue(Stats stat) const",
        "float Unit::GetTotalAuraModValue(UnitMods unitMod) const",
        "void Unit::SetStatFlatModifier(UnitMods unitMod, UnitModifierFlatType modifierType, float val)",
        "void Unit::SetStatPctModifier(UnitMods unitMod, UnitModifierPctType modifierType, float val)",
        "float Unit::GetFlatModifierValue(UnitMods unitMod, UnitModifierFlatType modifierType) const",
        "float Unit::GetPctModifierValue(UnitMods unitMod, UnitModifierPctType modifierType) const",
        "void Unit::UpdateUnitMod(UnitMods unitMod)",
        "SpellSchools Unit::GetSpellSchoolByAuraGroup(UnitMods unitMod) const",
        "Stats Unit::GetStatByAuraGroup(UnitMods unitMod) const",
        "float Unit::GetTotalAttackPowerValue(WeaponAttackType attType, bool includeWeapon /*= true*/) const",
        "float Unit::GetWeaponDamageRange(WeaponAttackType attType, WeaponDamageRange type) const",
        "uint32 Unit::GetBaseAttackTime(WeaponAttackType att) const",
    ]
    for sig in unit_fns:
        bodies.append(function(unit, sig, "Unit.cpp"))
    for sig in ("void Creature::UpdateLevelDependantStats()",
                "uint64 Creature::GetMaxHealthByLevel(uint8 level) const",
                "float Creature::GetBaseDamageForLevel(uint8 level) const",
                "float Creature::GetBaseArmorForLevel(uint8 level) const"):
        bodies.append(function(creature, sig, "Creature.cpp"))

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_DECLS.write_text("\n\n".join(decls) + "\n", encoding="utf-8")
    OUT_BODIES.write_text("\n\n".join(bodies) + "\n", encoding="utf-8")
    print(f"wrote {OUT_DECLS.name} ({len(decls)} blocks), {OUT_BODIES.name} ({len(bodies)} blocks) from {TC_ROOT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
