#!/usr/bin/env python3
"""Extract TrinityCore function bodies verbatim into a generated header.

The point of the differential probe is to be stronger than Python-vs-Python.
Hand-retyping the C++ into the probe would only prove the probe matches the
Python; instead this pulls the *actual* bodies out of the sibling TrinityCore
checkout at build time, so:

* a change in TrinityCore breaks the build or the comparison rather than
  silently diverging;
* the arithmetic runs in C++ ``float`` with C++ ``std::round``/``std::floor``
  semantics, which is a real difference from Python's ``double``.

Extracted bodies:
  DB2Manager::GetCurveValueAt(CurveInterpolationMode, span, float)  DB2Stores.cpp
  DetermineCurveType(CurveEntry const*, vector<DBCPosition2D> const&) DB2Stores.cpp
  ItemTemplate::GetDamage(uint32, float&, float&)                    ItemTemplate.cpp

Nothing else is extracted: the remaining stages are integer/table lookups where
Python and C++ cannot disagree.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

#: Resolved the way the rest of the workspace does it: walk up to the shared
#: parent of the sibling repositories, then join TrinityCore.  Override with
#: argv[1] or the Makefile's TC_ROOT.
WORKSPACE_PARENT = Path(__file__).resolve().parents[4].parent
TC_ROOT = Path(sys.argv[1] if len(sys.argv) > 1
               else WORKSPACE_PARENT / "TrinityCore")
OUT = Path(sys.argv[2] if len(sys.argv) > 2
           else Path(__file__).with_name("tc_extracted.inc"))

DB2_STORES = TC_ROOT / "src/server/game/DataStores/DB2Stores.cpp"
ITEM_TEMPLATE = TC_ROOT / "src/server/game/Entities/Item/ItemTemplate.cpp"


def extract_body(text: str, signature: str) -> str:
    """Return the brace-matched body of the function whose signature line matches."""
    index = text.find(signature)
    if index < 0:
        raise SystemExit(f"signature not found: {signature}")
    open_brace = text.index("{", index)
    depth = 0
    for position in range(open_brace, len(text)):
        if text[position] == "{":
            depth += 1
        elif text[position] == "}":
            depth -= 1
            if depth == 0:
                return text[open_brace:position + 1]
    raise SystemExit(f"unbalanced braces after {signature}")


def main() -> int:
    db2 = DB2_STORES.read_text(encoding="utf-8")
    item = ITEM_TEMPLATE.read_text(encoding="utf-8")

    curve_value = extract_body(
        db2, "float DB2Manager::GetCurveValueAt(CurveInterpolationMode mode,")
    determine = extract_body(
        db2, "static CurveInterpolationMode DetermineCurveType(")
    get_damage = extract_body(
        item, "void ItemTemplate::GetDamage(uint32 itemLevel, float& minDamage,")

    # GetDamage calls three member accessors; the probe supplies them as
    # file-local functions with the same names, so the body compiles unchanged.
    lines = [
        "// GENERATED by extract.py -- do not edit.",
        f"// TrinityCore: {TC_ROOT}",
        "",
        "static CurveInterpolationMode DetermineCurveType("
        "CurveEntry const* curve, std::vector<DBCPosition2D> const& points)",
        determine,
        "",
        "float DB2Manager_GetCurveValueAt(CurveInterpolationMode mode, "
        "std::span<DBCPosition2D const> points, float x)",
        curve_value,
        "",
        "void ItemTemplate_GetDamage(uint32 itemLevel, float& minDamage, "
        "float& maxDamage)",
        get_damage,
        "",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({sum(len(x.splitlines()) for x in lines)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
