#!/usr/bin/env python3
"""Extract TrinityCore swing / attack-table bodies verbatim into a generated header.

Part D of the combat-preparation research pass (swing scheduling, attack
outcome table).  The differential probe compiles the *actual* TrinityCore
code, so the Python oracle in ``weapon_combat.attack_table`` /
``weapon_combat.swing`` is compared against C++ ``float`` arithmetic and the
real band ordering, not against a re-typing of itself.

Extracted verbatim (function signature line through the matching brace):

  Unit.cpp   ApplyPercentModFloatVar, Unit::ApplyAttackTimePercentMod,
             Unit::UpdateAttackTimeField, Unit::resetAttackTimer,
             CalcMeleeAttackRageGain, Unit::RollMeleeOutcomeAgainst,
             Unit::MeleeSpellHitResult, Unit::GetUnitDodgeChance,
             Unit::GetUnitParryChance, Unit::GetUnitMissChance,
             Unit::GetUnitBlockChance, Unit::GetUnitCriticalChanceDone,
             Unit::GetUnitCriticalChanceTaken, Unit::GetUnitCriticalChanceAgainst,
             Unit::MeleeSpellMissChance
  Player.cpp Player::GetExpertiseDodgeOrParryReduction, Player::GetBlockPercent
  Util.h     CalculatePct, AddPct

``Player::GetBlockPercent`` is emitted as ``Player::Player_GetBlockPercent``
(rename only) so the stub can dispatch virtually.

Extracted as statement blocks and wrapped (mechanical edit: ``break;`` ->
``return;`` so the block compiles outside its ``switch``):

  Unit.cpp   the parry-haste block of Unit::DealMeleeDamage
             (``if (damageInfo->TargetState == VICTIMSTATE_PARRY && ...) { ... }``)
             -> ``static void ProbeParryHaste(Unit* victim)``
             ``case MELEE_HIT_CRIT:`` / ``case MELEE_HIT_BLOCK:`` /
             ``case MELEE_HIT_GLANCING:`` of Unit::CalculateMeleeDamage
             -> ``Unit::ProbeCrit/ProbeBlock/ProbeGlancing(Unit* victim, CalcDamageInfo* damageInfo)``

The probe supplies one stub class (``Unit``; ``Player``/``Creature``/
``TempSummon`` are aliases of it) whose accessors read a key/value
configuration, so every input the bodies consult is explicit.
"""

from __future__ import annotations

import sys
from pathlib import Path

WORKSPACE_PARENT = Path(__file__).resolve().parents[4].parent
TC_ROOT = Path(sys.argv[1] if len(sys.argv) > 1 else WORKSPACE_PARENT / "TrinityCore")
OUT = Path(sys.argv[2] if len(sys.argv) > 2 else Path(__file__).with_name("tc_swing_bodies.inc"))

UNIT = TC_ROOT / "src/server/game/Entities/Unit/Unit.cpp"
PLAYER = TC_ROOT / "src/server/game/Entities/Player/Player.cpp"
UTIL = TC_ROOT / "src/common/Utilities/Util.h"


def definition(text: str, signature: str) -> str:
    """Signature (from its first character) through the brace-matched body."""
    start = text.find(signature)
    if start < 0:
        raise SystemExit(f"signature not found: {signature}")
    if text.find(signature, start + 1) >= 0:
        raise SystemExit(f"signature not unique: {signature}")
    return text[start:_match(text, text.index("{", start)) + 1]


def block_after(text: str, anchor: str, start_at: int = 0) -> str:
    """The first brace-matched block after ``anchor``."""
    start = text.find(anchor, start_at)
    if start < 0:
        raise SystemExit(f"anchor not found: {anchor}")
    open_brace = text.index("{", start)
    return text[open_brace:_match(text, open_brace) + 1]


def between(text: str, first: str, second: str, start_at: int = 0) -> str:
    a = text.find(first, start_at)
    if a < 0:
        raise SystemExit(f"anchor not found: {first}")
    b = text.find(second, a)
    if b < 0:
        raise SystemExit(f"anchor not found: {second}")
    return text[a + len(first):b]


def _match(text: str, open_brace: int) -> int:
    depth = 0
    for position in range(open_brace, len(text)):
        if text[position] == "{":
            depth += 1
        elif text[position] == "}":
            depth -= 1
            if depth == 0:
                return position
    raise SystemExit("unbalanced braces")


def main() -> int:
    unit = UNIT.read_text(encoding="utf-8")
    player = PLAYER.read_text(encoding="utf-8")
    util = UTIL.read_text(encoding="utf-8")

    parts: list[str] = [
        "// GENERATED by extract.py -- do not edit, do not commit.",
        f"// TrinityCore: {TC_ROOT}",
        "",
        "template <class T, class U>",
        definition(util, "inline T CalculatePct(T base, U pct)"),
        "",
        "template <class T, class U>",
        definition(util, "inline T AddPct(T &base, U pct)"),
        "",
    ]
    for sig in (
        "void ApplyPercentModFloatVar(float& var, float val, bool apply)",
        "void Unit::UpdateAttackTimeField(WeaponAttackType att)",
        "void Unit::ApplyAttackTimePercentMod(WeaponAttackType att, float val, bool apply)",
        "void Unit::resetAttackTimer(WeaponAttackType type)",
        "static uint32 CalcMeleeAttackRageGain(Unit const* attacker, WeaponAttackType attType)",
        "MeleeHitOutcome Unit::RollMeleeOutcomeAgainst(Unit const* victim, WeaponAttackType attType) const",
        "SpellMissInfo Unit::MeleeSpellHitResult(Unit* victim, SpellInfo const* spellInfo) const",
        "float Unit::GetUnitDodgeChance(WeaponAttackType attType, Unit const* victim) const",
        "float Unit::GetUnitParryChance(WeaponAttackType attType, Unit const* victim) const",
        "float Unit::GetUnitMissChance() const",
        "float Unit::GetUnitBlockChance(WeaponAttackType /*attType*/, Unit const* victim) const",
        "float Unit::GetUnitCriticalChanceDone(WeaponAttackType attackType) const",
        "float Unit::GetUnitCriticalChanceTaken(Unit const* attacker, WeaponAttackType attackType, float critDone) const",
        "float Unit::GetUnitCriticalChanceAgainst(WeaponAttackType attackType, Unit const* victim) const",
        "float Unit::MeleeSpellMissChance(Unit const* victim, WeaponAttackType attType, SpellInfo const* spellInfo) const",
    ):
        parts += [definition(unit, sig), ""]
    parts += [definition(player, "float Player::GetExpertiseDodgeOrParryReduction(WeaponAttackType attType) const"), ""]
    # Mechanical rename: the stub's Unit::GetBlockPercent reproduces the virtual dispatch
    # (Unit.h:987 base returns 30.0f; Player overrides) and calls the verbatim Player body.
    block_pct = definition(player, "float Player::GetBlockPercent(uint8 attackerLevel) const")
    parts += [block_pct.replace("float Player::GetBlockPercent(", "float Player::Player_GetBlockPercent(", 1), ""]

    calc = unit.index("void Unit::CalculateMeleeDamage(")
    deal = unit.index("void Unit::DealMeleeDamage(")
    parry = block_after(unit, "if (damageInfo->TargetState == VICTIMSTATE_PARRY &&", deal)
    parts += ["static void ProbeParryHaste(Unit* victim)", parry, ""]
    crit = block_after(unit, "case MELEE_HIT_CRIT:", calc)
    parts += ["void Unit::ProbeCrit(Unit* victim, CalcDamageInfo* damageInfo)", crit.replace("break;", "return;"), ""]
    block = between(unit, "case MELEE_HIT_BLOCK:", "case MELEE_HIT_GLANCING:", calc)
    parts += ["void Unit::ProbeBlock(Unit* victim, CalcDamageInfo* damageInfo)",
              "{" + block.replace("break;", "return;") + "}", ""]
    glancing = block_after(unit, "case MELEE_HIT_GLANCING:", calc)
    parts += ["void Unit::ProbeGlancing(Unit* victim, CalcDamageInfo* damageInfo)",
              glancing.replace("break;", "return;"), ""]

    OUT.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
