// Differential probe for weapon_combat part D (swing scheduling + attack table).
//
// tc_swing_bodies.inc is generated by extract.py from the sibling TrinityCore
// checkout (7f3d43b): RollMeleeOutcomeAgainst, MeleeSpellHitResult, every
// chance getter, MeleeSpellMissChance, ApplyAttackTimePercentMod,
// UpdateAttackTimeField, resetAttackTimer, CalcMeleeAttackRageGain,
// Player::GetExpertiseDodgeOrParryReduction, Player::GetBlockPercent, the
// DealMeleeDamage parry-haste block and the crit/block/glancing cases of
// CalculateMeleeDamage.  This file supplies one stub class whose accessors
// read a key/value configuration; nothing of the arithmetic or ordering is
// re-typed here.
//
// Build: make   (g++ -std=c++20 -O0 -ffp-contract=off)
// Protocol (one request per line, one reply line):
//   clear                         -> ok        (drop all configuration)
//   set <key> <number>            -> ok        (see Unit accessors for keys; "a." attacker, "v." victim, "s." spell)
//   white <0|1>                   -> RLE of RollMeleeOutcomeAgainst over urand = 0..9999: "outcome@first ..."
//   spell                         -> RLE of MeleeSpellHitResult over urand = 0..9999
//   chance <dodge|parry|block|miss|missspell|crit> <att>   -> float (%.9g)
//   atkmod <timer> <base> <pct> <val> <apply>  -> "<timer> <pct %.9g> <field>"
//   reset <base> <pct> <att>      -> timer
//   parry <off> <base> <baseoff> <basemh> <haveoh> -> "<off> <base>"
//   rage <base> <att>             -> uint32
//   blockpct <shieldblock> <armorconstant> -> float
//   pct <base> <pct>              -> CalculatePct<uint32,float>
//   crit <damage> <multiplier>    -> damage after the MELEE_HIT_CRIT case
//   block <damage> <victimIsPlayer> <shieldblock> <armorconstant> <blockcrit> <critmult> -> "<damage> <blocked>"
//   glancing <damage> <attackerLevel> <victimLevel> -> "<damage> <clean>"
//   f32 <expr-op> ...             (not provided: Python owns binary32 emulation)

#include <algorithm>
#include <array>
#include <cmath>
#include <cstdint>
#include <cstdio>
#include <functional>
#include <iostream>
#include <list>
#include <map>
#include <sstream>
#include <string>
#include <vector>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

#define TC_LOG_DEBUG(...) ((void)0)

using uint8 = std::uint8_t;
using int32 = std::int32_t;
using uint32 = std::uint32_t;

static std::map<std::string, double> g_cfg;
static double cf(std::string const& key, double def = 0.0)
{
    auto it = g_cfg.find(key);
    return it == g_cfg.end() ? def : it->second;
}

static uint32 g_roll = 0;
uint32 urand(uint32 /*min*/, uint32 /*max*/) { return g_roll; }

enum WeaponAttackType : uint8 { BASE_ATTACK = 0, OFF_ATTACK = 1, RANGED_ATTACK = 2, MAX_ATTACK };
enum TypeID { TYPEID_UNIT = 5, TYPEID_PLAYER = 6 };
enum MeleeHitOutcome : uint8
{
    MELEE_HIT_EVADE, MELEE_HIT_MISS, MELEE_HIT_DODGE, MELEE_HIT_BLOCK, MELEE_HIT_PARRY,
    MELEE_HIT_GLANCING, MELEE_HIT_CRIT, MELEE_HIT_CRUSHING, MELEE_HIT_NORMAL
};
enum SpellMissInfo : uint8
{
    SPELL_MISS_NONE = 0, SPELL_MISS_MISS = 1, SPELL_MISS_RESIST = 2, SPELL_MISS_DODGE = 3, SPELL_MISS_PARRY = 4,
    SPELL_MISS_BLOCK = 5, SPELL_MISS_EVADE = 6, SPELL_MISS_IMMUNE = 7, SPELL_MISS_IMMUNE2 = 8, SPELL_MISS_DEFLECT = 9,
    SPELL_MISS_ABSORB = 10, SPELL_MISS_REFLECT = 11
};
enum AuraType : uint32
{
    SPELL_AURA_MOD_PARRY_PERCENT = 47, SPELL_AURA_MOD_DODGE_PERCENT = 49, SPELL_AURA_MOD_BLOCK_PERCENT = 51,
    SPELL_AURA_MOD_WEAPON_CRIT_PERCENT = 52, SPELL_AURA_MOD_HIT_CHANCE = 54, SPELL_AURA_MOD_CRIT_DAMAGE_BONUS = 163,
    SPELL_AURA_MOD_CRIT_CHANCE_VERSUS_TARGET_HEALTH = 183, SPELL_AURA_MOD_ATTACKER_MELEE_HIT_CHANCE = 184,
    SPELL_AURA_MOD_ATTACKER_RANGED_HIT_CHANCE = 185, SPELL_AURA_MOD_ATTACKER_MELEE_CRIT_CHANCE = 187,
    SPELL_AURA_MOD_ATTACKER_SPELL_AND_WEAPON_CRIT_CHANCE = 197, SPELL_AURA_IGNORE_COMBAT_RESULT = 202,
    SPELL_AURA_MOD_EXPERTISE = 240, SPELL_AURA_MOD_COMBAT_RESULT_CHANCE = 248, SPELL_AURA_MOD_ENEMY_DODGE = 251,
    SPELL_AURA_MOD_BLOCK_CRIT_CHANCE = 253, SPELL_AURA_DEFLECT_SPELLS = 287, SPELL_AURA_IGNORE_HIT_DIRECTION = 288,
    SPELL_AURA_MOD_CRIT_PCT = 290, SPELL_AURA_MOD_CRIT_CHANCE_FOR_CASTER = 306, SPELL_AURA_MOD_AUTOATTACK_CRIT_CHANCE = 334,
    SPELL_AURA_MOD_CRIT_CHANCE_FOR_CASTER_PET = 339, SPELL_AURA_IGNORE_DUAL_WIELD_HIT_PENALTY = 458,
    SPELL_AURA_MOD_CRITICAL_BLOCK_AMOUNT = 638,
};
enum SpellAttr0 : uint32 { SPELL_ATTR0_NO_ACTIVE_DEFENSE = 0x00200000 };
enum SpellAttr3 : uint32 { SPELL_ATTR3_NO_AVOIDANCE = 0x00000040 };
enum SpellAttr7 : uint32 { SPELL_ATTR7_NO_ATTACK_DODGE = 0x00800000, SPELL_ATTR7_NO_ATTACK_PARRY = 0x01000000, SPELL_ATTR7_NO_ATTACK_MISS = 0x02000000 };
enum SpellAttr8 : uint32 { SPELL_ATTR8_NO_ATTACK_BLOCK = 0x00000001 };
enum SpellCustomAttributes : uint32 { SPELL_ATTR0_CU_REQ_CASTER_BEHIND_TARGET = 0x00020000 };
enum SpellDmgClass { SPELL_DAMAGE_CLASS_NONE = 0, SPELL_DAMAGE_CLASS_MAGIC = 1, SPELL_DAMAGE_CLASS_MELEE = 2, SPELL_DAMAGE_CLASS_RANGED = 3 };
enum class SpellModOp : uint8 { HitChance = 7 };
enum CurrentSpellTypes { CURRENT_MELEE_SPELL = 0, CURRENT_GENERIC_SPELL = 1, CURRENT_CHANNELED_SPELL = 2, CURRENT_AUTOREPEAT_SPELL = 3, CURRENT_MAX_SPELL };
enum : uint32 { UNIT_STATE_CONTROLLED = 0x1000 };
enum : uint32
{
    CREATURE_FLAG_EXTRA_NO_PARRY = 0x4, CREATURE_FLAG_EXTRA_NO_PARRY_HASTEN = 0x8, CREATURE_FLAG_EXTRA_NO_BLOCK = 0x10,
    CREATURE_FLAG_EXTRA_NO_CRUSHING_BLOWS = 0x20, CREATURE_FLAG_EXTRA_NO_CRIT = 0x20000,
};
enum : uint32 { HITINFO_CRITICALHIT = 0x200, HITINFO_BLOCK = 0x2000, HITINFO_GLANCING = 0x10000 };
enum : uint32 { VICTIMSTATE_HIT = 1, VICTIMSTATE_DODGE = 2, VICTIMSTATE_PARRY = 3 };
enum : uint8 { INVENTORY_SLOT_BAG_0 = 255, EQUIPMENT_SLOT_OFFHAND = 16 };
enum InventoryType : uint8 { INVTYPE_NON_EQUIP = 0, INVTYPE_SHIELD = 14 };
enum class ExpectedStatType : uint8 { ArmorConstant = 5 };
enum Classes : uint8 { CLASS_NONE = 0 };

struct SpellInfo
{
    uint32 DmgClass = SPELL_DAMAGE_CLASS_MELEE;
    bool HasAttribute(SpellAttr0 a) const { return (uint32(cf("s.attr0")) & a) != 0; }
    bool HasAttribute(SpellAttr3 a) const { return (uint32(cf("s.attr3")) & a) != 0; }
    bool HasAttribute(SpellAttr7 a) const { return (uint32(cf("s.attr7")) & a) != 0; }
    bool HasAttribute(SpellAttr8 a) const { return (uint32(cf("s.attr8")) & a) != 0; }
    bool HasAttribute(SpellCustomAttributes a) const { return (uint32(cf("s.attrcu")) & a) != 0; }
};

struct Spell {};

struct ObjectGuid
{
    double v = 0;
    bool operator==(ObjectGuid const& o) const { return v == o.v; }
};

struct AuraEffect
{
    int32 misc = 0;
    bool IsAffectingSpell(SpellInfo const*) const { return true; }
    int32 GetMiscValue() const { return misc; }
    int32 GetMiscValueB() const { return 0; }
    ObjectGuid GetCasterGUID() const { return {}; }
};
using AuraEffectList = std::list<AuraEffect const*>;

template <class T>
struct UFValue
{
    T value{};
    operator T() const { return value; }
    T operator*() const { return value; }
};

struct ActivePlayerData
{
    UFValue<float> DodgePercentage, ParryPercentage, BlockPercentage, CritPercentage, OffhandCritPercentage, RangedCritPercentage;
    UFValue<int32> MainhandExpertise, OffhandExpertise, ShieldBlock;
};

struct ItemTemplate
{
    InventoryType inv = INVTYPE_NON_EQUIP;
    InventoryType GetInventoryType() const { return inv; }
};

struct Item
{
    bool broken = false;
    ItemTemplate tmpl;
    bool IsBroken() const { return broken; }
    ItemTemplate const* GetTemplate() const { return &tmpl; }
};

struct CreatureTemplate { uint32 flags_extra = 0; };

namespace UF
{
struct UnitData { uint32 AttackRoundBaseTime[2]; uint32 RangedAttackRoundBaseTime; float ModHaste; float ModRangedHaste; };
}

static double g_field = 0;
struct MutableFieldStub
{
    template <class... A> MutableFieldStub& ModifyValue(A&&...) { return *this; }
};
template <class T> void SetUpdateFieldValue(MutableFieldStub&, T value) { g_field = double(value); }
void ApplyPercentModUpdateFieldValue(MutableFieldStub&, float, bool) {}

static float g_armorConstant = 0.0f;
struct DB2ManagerStub
{
    float EvaluateExpectedStat(ExpectedStatType, uint32, int32, uint32, Classes, int32) const { return g_armorConstant; }
};
static DB2ManagerStub sDB2Manager;

struct CalcDamageInfo
{
    struct Unit* Attacker = nullptr;
    struct Unit* Target = nullptr;
    uint32 DamageSchoolMask = 1;
    uint32 Damage = 0;
    uint32 OriginalDamage = 0;
    uint32 Absorb = 0;
    uint32 Resist = 0;
    uint32 Blocked = 0;
    uint32 HitInfo = 0;
    uint32 TargetState = 0;
    uint32 CleanDamage = 0;
};

struct Unit;
using Player = Unit;
using Creature = Unit;
using TempSummon = Unit;

void ApplyPercentModFloatVar(float& var, float val, bool apply);

struct Unit
{
    std::string p;
    explicit Unit(std::string prefix) : p(std::move(prefix)) {}

    // --- state the extracted bodies read ----------------------------------
    std::array<uint32, MAX_ATTACK> m_baseAttackSpeed{};
    std::array<float, MAX_ATTACK> m_modAttackSpeedPct{1.0f, 1.0f, 1.0f};
    std::array<uint32, MAX_ATTACK> m_attackTimer{};
    Spell* m_currentSpells[CURRENT_MAX_SPELL] = {};
    float m_modMeleeHitChance = 0.0f;
    float m_modRangedHitChance = 0.0f;
    MutableFieldStub m_values;
    UF::UnitData m_unitData{};
    ActivePlayerData apd;
    ActivePlayerData const* m_activePlayerData = &apd;
    CreatureTemplate ctmpl;
    Item mainhand, offhand;
    AuraEffectList icr;
    std::vector<AuraEffect> icrStore;
    Spell dummySpell;

    double c(std::string const& k, double d = 0.0) const { return cf(p + k, d); }

    void sync()
    {
        bool player = c("player") != 0;
        m_currentSpells[CURRENT_MELEE_SPELL] = c("meleespell") != 0 ? &dummySpell : nullptr;
        m_modMeleeHitChance = float(c("hitmelee", player ? 7.5 : 0.0));
        m_modRangedHitChance = float(c("hitranged", player ? 7.5 : 0.0));
        apd.DodgePercentage.value = float(c("dodgepct"));
        apd.ParryPercentage.value = float(c("parrypct"));
        apd.BlockPercentage.value = float(c("blockpct"));
        apd.CritPercentage.value = float(c("crit"));
        apd.OffhandCritPercentage.value = float(c("critoh", c("crit")));
        apd.RangedCritPercentage.value = float(c("critranged", c("crit")));
        apd.MainhandExpertise.value = int32(c("expmh"));
        apd.OffhandExpertise.value = int32(c("expoh"));
        apd.ShieldBlock.value = int32(c("shieldblock"));
        ctmpl.flags_extra = uint32(c("flags_extra"));
        mainhand.broken = c("weaponbroken") != 0;
        offhand.broken = c("shieldbroken") != 0;
        offhand.tmpl.inv = c("shield") != 0 ? INVTYPE_SHIELD : INVTYPE_NON_EQUIP;
        icrStore.clear();
        icr.clear();
        if (c("icr.dodge") != 0) icrStore.push_back({MELEE_HIT_DODGE});
        if (c("icr.parry") != 0) icrStore.push_back({MELEE_HIT_PARRY});
        if (c("icr.block") != 0) icrStore.push_back({MELEE_HIT_BLOCK});
        for (AuraEffect const& e : icrStore) icr.push_back(&e);
    }

    // --- accessors --------------------------------------------------------
    TypeID GetTypeId() const { return c("player") != 0 ? TYPEID_PLAYER : TYPEID_UNIT; }
    Player const* ToPlayer() const { return c("player") != 0 ? this : nullptr; }
    Player* ToPlayer() { return c("player") != 0 ? this : nullptr; }
    Creature const* ToCreature() const { return c("player") != 0 ? nullptr : this; }
    Creature* ToCreature() { return c("player") != 0 ? nullptr : this; }
    TempSummon const* ToTempSummon() const { return c("tempsummon") != 0 ? this : nullptr; }
    ObjectGuid GetGUID() const { return {c("guid")}; }
    ObjectGuid GetSummonerGUID() const { return {c("summoner")}; }
    bool IsTotem() const { return c("totem") != 0; }
    bool IsPet() const { return c("pet") != 0; }
    bool IsControlledByPlayer() const { return c("cbp", c("player")) != 0; }
    bool IsEvadingAttacks() const { return c("evading") != 0; }
    bool IsStandState() const { return c("stand", 1) != 0; }
    bool IsInFeralForm() const { return c("feral") != 0; }
    bool haveOffhandWeapon() const { return c("offhand") != 0; }
    bool CanParry() const { return c("canparry") != 0; }
    bool CanBlock() const { return c("canblock") != 0; }
    bool IsBlockCritical() const { return c("blockcrit") != 0; }
    bool HealthBelowPct(float) const { return false; }
    uint8 GetLevelForTarget(Unit const*) const { return uint8(c("level", 90)); }
    uint8 GetLevel() const { return uint8(c("rawlevel", c("level", 90))); }
    CreatureTemplate const* GetCreatureTemplate() const { return &ctmpl; }
    bool HasInArc(float, Unit const*, float = 2.0f) const { return c("facing", 1) != 0; }
    bool HasAuraType(AuraType t) const { return c("has." + std::to_string(t)) != 0 || c("aura." + std::to_string(t)) != 0; }
    bool IsNonMeleeSpellCast(bool, bool = false, bool = false, bool = false, bool = true) const { return c("casting") != 0; }
    bool HasUnitState(uint32 s) const { return (s & UNIT_STATE_CONTROLLED) && c("controlled") != 0; }
    float GetTotalAuraModifier(AuraType t) const { return float(c("aura." + std::to_string(t))); }
    float GetTotalAuraModifier(AuraType t, std::function<bool(AuraEffect const*)> const&) const { return float(c("aura." + std::to_string(t))); }
    float GetTotalAuraModifierByMiscValue(AuraType t, int32 misc) const { return float(c("auramisc." + std::to_string(t) + "." + std::to_string(misc))); }
    float GetTotalAuraMultiplier(AuraType t) const { return float(c("mult." + std::to_string(t), 1.0)); }
    float GetTotalAuraMultiplierByMiscMask(AuraType t, uint32) const { return float(c("mult." + std::to_string(t), 1.0)); }
    AuraEffectList const& GetAuraEffectsByType(AuraType) const { return icr; }
    Player* GetSpellModOwner() const { return c("modowner", c("player")) != 0 ? const_cast<Unit*>(this) : nullptr; }
    template <class T> void ApplySpellMod(SpellInfo const*, SpellModOp op, T& value, Spell* = nullptr) const
    {
        if (op == SpellModOp::HitChance)
            value += T(c("spellmod_hit"));
    }
    float GetMechanicResistChance(SpellInfo const*) const { return float(c("resist")); }
    Item* GetWeaponForAttack(WeaponAttackType att, bool) const
    {
        if (att == BASE_ATTACK && c("weapon", 1) != 0 && !mainhand.broken) return const_cast<Item*>(&mainhand);
        return nullptr;
    }
    Item* GetUseableItemByPos(uint8, uint8) const { return c("shield") != 0 ? const_cast<Item*>(&offhand) : nullptr; }
    uint32 GetBaseAttackTime(WeaponAttackType att) const { return m_baseAttackSpeed[att]; }
    uint32 getAttackTimer(WeaponAttackType type) const { return m_attackTimer[type]; }
    void setAttackTimer(WeaponAttackType type, uint32 time) { m_attackTimer[type] = time; }

    // --- extracted (tc_swing_bodies.inc) -----------------------------------
    void UpdateAttackTimeField(WeaponAttackType att);
    void ApplyAttackTimePercentMod(WeaponAttackType att, float val, bool apply);
    void resetAttackTimer(WeaponAttackType type);
    MeleeHitOutcome RollMeleeOutcomeAgainst(Unit const* victim, WeaponAttackType attType) const;
    SpellMissInfo MeleeSpellHitResult(Unit* victim, SpellInfo const* spellInfo) const;
    float GetUnitDodgeChance(WeaponAttackType attType, Unit const* victim) const;
    float GetUnitParryChance(WeaponAttackType attType, Unit const* victim) const;
    float GetUnitMissChance() const;
    float GetUnitBlockChance(WeaponAttackType attType, Unit const* victim) const;
    float GetUnitCriticalChanceDone(WeaponAttackType attackType) const;
    float GetUnitCriticalChanceTaken(Unit const* attacker, WeaponAttackType attackType, float critDone) const;
    float GetUnitCriticalChanceAgainst(WeaponAttackType attackType, Unit const* victim) const;
    float MeleeSpellMissChance(Unit const* victim, WeaponAttackType attType, SpellInfo const* spellInfo) const;
    float GetExpertiseDodgeOrParryReduction(WeaponAttackType attType) const;
    float Player_GetBlockPercent(uint8 attackerLevel) const;
    // virtual Unit::GetBlockPercent (Unit.h:987 `return 30.0f`), overridden by Player only
    float GetBlockPercent(uint8 attackerLevel) const { return GetTypeId() == TYPEID_PLAYER ? Player_GetBlockPercent(attackerLevel) : 30.0f; }
    void ProbeCrit(Unit* victim, CalcDamageInfo* damageInfo);
    void ProbeBlock(Unit* victim, CalcDamageInfo* damageInfo);
    void ProbeGlancing(Unit* victim, CalcDamageInfo* damageInfo);
};

#include "tc_swing_bodies.inc"

static char const* OutcomeName(MeleeHitOutcome o)
{
    switch (o)
    {
        case MELEE_HIT_EVADE: return "evade";
        case MELEE_HIT_MISS: return "miss";
        case MELEE_HIT_DODGE: return "dodge";
        case MELEE_HIT_BLOCK: return "block";
        case MELEE_HIT_PARRY: return "parry";
        case MELEE_HIT_GLANCING: return "glancing";
        case MELEE_HIT_CRIT: return "crit";
        case MELEE_HIT_CRUSHING: return "crushing";
        case MELEE_HIT_NORMAL: return "normal";
    }
    return "?";
}

static char const* MissName(SpellMissInfo m)
{
    switch (m)
    {
        case SPELL_MISS_NONE: return "none";
        case SPELL_MISS_MISS: return "miss";
        case SPELL_MISS_RESIST: return "resist";
        case SPELL_MISS_DODGE: return "dodge";
        case SPELL_MISS_PARRY: return "parry";
        case SPELL_MISS_BLOCK: return "block";
        case SPELL_MISS_DEFLECT: return "deflect";
        default: return "other";
    }
}

static std::string Rle(std::function<char const*(uint32)> const& at)
{
    std::ostringstream out;
    char const* last = nullptr;
    for (uint32 r = 0; r < 10000; ++r)
    {
        char const* name = at(r);
        if (!last || std::string(name) != last)
        {
            if (last)
                out << ' ';
            out << name << '@' << r;
            last = name;
        }
    }
    return out.str();
}

static std::string F(double v)
{
    char buf[64];
    std::snprintf(buf, sizeof buf, "%.9g", v);
    return buf;
}

int main()
{
    std::string line;
    while (std::getline(std::cin, line))
    {
        std::istringstream in(line);
        std::string cmd;
        in >> cmd;
        Unit A("a."), V("v.");
        A.sync();
        V.sync();
        std::string reply;
        if (cmd == "clear")
        {
            g_cfg.clear();
            reply = "ok";
        }
        else if (cmd == "set")
        {
            std::string key;
            double value;
            in >> key >> value;
            g_cfg[key] = value;
            reply = "ok";
        }
        else if (cmd == "white")
        {
            int att;
            in >> att;
            reply = Rle([&](uint32 r) { g_roll = r; return OutcomeName(A.RollMeleeOutcomeAgainst(&V, WeaponAttackType(att))); });
        }
        else if (cmd == "spell")
        {
            SpellInfo info;
            info.DmgClass = cf("s.ranged") != 0 ? SPELL_DAMAGE_CLASS_RANGED : SPELL_DAMAGE_CLASS_MELEE;
            reply = Rle([&](uint32 r) { g_roll = r; return MissName(A.MeleeSpellHitResult(&V, &info)); });
        }
        else if (cmd == "chance")
        {
            std::string which;
            int att;
            in >> which >> att;
            WeaponAttackType t = WeaponAttackType(att);
            SpellInfo info;
            if (which == "dodge") reply = F(A.GetUnitDodgeChance(t, &V));
            else if (which == "parry") reply = F(A.GetUnitParryChance(t, &V));
            else if (which == "block") reply = F(A.GetUnitBlockChance(t, &V));
            else if (which == "miss") reply = F(A.MeleeSpellMissChance(&V, t, nullptr));
            else if (which == "missspell") reply = F(A.MeleeSpellMissChance(&V, t, &info));
            else if (which == "crit") reply = F(A.GetUnitCriticalChanceAgainst(t, &V));
            else reply = "error";
        }
        else if (cmd == "atkmod")
        {
            uint32 timer, base;
            float pct, val;
            int apply;
            in >> timer >> base >> pct >> val >> apply;
            A.m_attackTimer[BASE_ATTACK] = timer;
            A.m_baseAttackSpeed[BASE_ATTACK] = base;
            A.m_modAttackSpeedPct[BASE_ATTACK] = pct;
            A.ApplyAttackTimePercentMod(BASE_ATTACK, val, apply != 0);
            reply = std::to_string(A.m_attackTimer[BASE_ATTACK]) + " " + F(A.m_modAttackSpeedPct[BASE_ATTACK]) + " " + std::to_string(uint32(g_field));
        }
        else if (cmd == "reset")
        {
            uint32 base;
            float pct;
            int att;
            in >> base >> pct >> att;
            A.m_baseAttackSpeed[att] = base;
            A.m_modAttackSpeedPct[att] = pct;
            A.resetAttackTimer(WeaponAttackType(att));
            reply = std::to_string(A.m_attackTimer[att]);
        }
        else if (cmd == "parry")
        {
            uint32 off, base, baseoff, basemh;
            in >> off >> base >> baseoff >> basemh;
            V.m_attackTimer[OFF_ATTACK] = off;
            V.m_attackTimer[BASE_ATTACK] = base;
            V.m_baseAttackSpeed[OFF_ATTACK] = baseoff;
            V.m_baseAttackSpeed[BASE_ATTACK] = basemh;
            ProbeParryHaste(&V);
            reply = std::to_string(V.m_attackTimer[OFF_ATTACK]) + " " + std::to_string(V.m_attackTimer[BASE_ATTACK]);
        }
        else if (cmd == "rage")
        {
            uint32 base;
            int att;
            in >> base >> att;
            A.m_baseAttackSpeed[att] = base;
            reply = std::to_string(CalcMeleeAttackRageGain(&A, WeaponAttackType(att)));
        }
        else if (cmd == "blockpct")
        {
            int32 sb;
            float ac;
            in >> sb >> ac;
            V.apd.ShieldBlock.value = sb;
            g_armorConstant = ac;
            g_cfg["v.player"] = 1;
            V.sync();
            V.apd.ShieldBlock.value = sb;
            reply = F(V.GetBlockPercent(90));
        }
        else if (cmd == "pct")
        {
            uint32 base;
            float pct;
            in >> base >> pct;
            reply = std::to_string(CalculatePct(base, pct));
        }
        else if (cmd == "crit")
        {
            uint32 dmg;
            double mult;
            in >> dmg >> mult;
            g_cfg["a.mult.163"] = mult;
            A.sync();
            CalcDamageInfo info;
            info.Damage = dmg;
            A.ProbeCrit(&V, &info);
            reply = std::to_string(info.Damage);
        }
        else if (cmd == "block")
        {
            uint32 dmg;
            int player, bc;
            int32 sb;
            float ac;
            double cm;
            in >> dmg >> player >> sb >> ac >> bc >> cm;
            g_cfg["v.player"] = player;
            g_cfg["v.blockcrit"] = bc;
            g_cfg["a.mult.638"] = cm;
            A.sync();
            V.sync();
            V.apd.ShieldBlock.value = sb;
            g_armorConstant = ac;
            CalcDamageInfo info;
            info.Damage = dmg;
            info.Target = &V;
            A.ProbeBlock(&V, &info);
            reply = std::to_string(info.Damage) + " " + std::to_string(info.Blocked);
        }
        else if (cmd == "glancing")
        {
            uint32 dmg;
            int al, vl;
            in >> dmg >> al >> vl;
            g_cfg["a.rawlevel"] = al;
            g_cfg["v.rawlevel"] = vl;
            CalcDamageInfo info;
            info.Damage = dmg;
            A.ProbeGlancing(&V, &info);
            reply = std::to_string(info.Damage) + " " + std::to_string(info.CleanDamage);
        }
        else
            reply = "error";
        std::cout << reply << std::endl;
    }
    return 0;
}
