#!/usr/bin/env python3
"""Extract TrinityCore chain / smart-selection code verbatim into generated headers.

The C++ side of the Track D differential is Trinity's own text compiled against
minimal stubs (``probe.cpp``).  ``Containers.h`` (``RandomResize``,
``SelectRandomContainerElement``, ``RandomShuffle``) is included directly from
the checkout; ``urand`` / ``rand32`` are the probe's scripted replacements.

Extracted verbatim (TrinityCore @ 7f3d43b):
  DBCEnums.h        enum class SpellEffectAttributes (+ DEFINE_ENUM_FLAG)
  SpellDefines.h    enum class SpellModOp
  Position.h        the distance block GetExactDist2dSq .. IsInDist(Position const*)
  Position.cpp      Position::NormalizeOrientation
  Object.cpp        WorldObject::_IsWithinDist, WorldObject::IsWithinDist, WorldObject::GetDistanceOrder
  Player.cpp        Player::ApplySpellMod (template body)
  Spell.cpp         Spell::SearchChainTargets, Trinity::SelectRandomInjuredTargets,
                    Trinity::SortTargetsWithPriorityRules
  Spell.h           struct TargetPriorityRule, the std::array SortTargetsWithPriorityRules overload
  CommonPredicates.h/.cpp  class HealthPctOrderPred, operator()(WorldObject const*, WorldObject const*)
  spell_priest.cpp  spell_pri_power_word_radiance::GetRadianceRules

Cut points (stubbed in probe.cpp): ``Spell::SearchAreaTargets`` (returns the
driver's candidate list in the driver's order; the area/relation check is Track
B/C's), ``Spell::IsWithinLOS`` (driver table), ``WorldObject::HasInArc`` (driver
flag per object), ``Spell::GetMinMaxRange`` (driver value),
``Player::GetSpellModValues`` (driver flat/pct), ``Unit::IsInRaidWith`` (driver
table), ``Creature::IsTreatedAsRaidUnit`` (driver flag).
"""

from __future__ import annotations

import sys
from pathlib import Path

WORKSPACE_PARENT = Path(__file__).resolve().parents[5]
TC_ROOT = Path(sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] else WORKSPACE_PARENT / "TrinityCore")
OUT_DIR = Path(sys.argv[2] if len(sys.argv) > 2 else Path(__file__).parent)
OUT_DECLS = OUT_DIR / "tc_chain_decls.inc"
OUT_BODIES = OUT_DIR / "tc_chain_bodies.inc"
G = TC_ROOT / "src/server/game"


def read(rel: str) -> str:
    return (G / rel).read_text(encoding="utf-8")


def braced(text: str, start: int) -> tuple[int, int]:
    open_brace = text.index("{", start)
    depth = 0
    for pos in range(open_brace, len(text)):
        if text[pos] == "{":
            depth += 1
        elif text[pos] == "}":
            depth -= 1
            if depth == 0:
                return open_brace, pos + 1
    raise SystemExit("unbalanced braces")


def unique(text: str, needle: str, source: str) -> int:
    start = text.find(needle)
    if start < 0:
        raise SystemExit(f"not found in {source}: {needle}")
    if text.find(needle, start + 1) >= 0:
        raise SystemExit(f"not unique in {source}: {needle}")
    return start


def block(text: str, header: str, source: str, suffix: str = "") -> str:
    start = unique(text, header, source)
    line = text.count("\n", 0, start) + 1
    _, end = braced(text, start)
    return f"// {source}:{line}\n{text[start:end]}{suffix}\n"


def between(text: str, first: str, last: str, source: str) -> str:
    a = unique(text, first, source)
    b = text.index(last, a) + len(last)
    line = text.count("\n", 0, a) + 1
    return f"// {source}:{line}\n{text[a:b]}\n"


def main() -> int:
    dbc = read("DataStores/DBCEnums.h")
    spelldefs = read("Spells/SpellDefines.h")
    pos_h = read("Entities/Object/Position.h")
    pos_cpp = read("Entities/Object/Position.cpp")
    obj = read("Entities/Object/Object.cpp")
    player = read("Entities/Player/Player.cpp")
    spell = read("Spells/Spell.cpp")
    spell_h = read("Spells/Spell.h")
    preds = read("Miscellaneous/CommonPredicates.cpp")
    preds_h = read("Miscellaneous/CommonPredicates.h")
    priest = (TC_ROOT / "src/server/scripts/Spells/spell_priest.cpp").read_text(encoding="utf-8")

    decls = [
        "// GENERATED by tools/tc_target_chain_probe/extract.py from TrinityCore -- do not edit",
        block(dbc, "enum class SpellEffectAttributes\n", "DBCEnums.h", ";"),
        "DEFINE_ENUM_FLAG(SpellEffectAttributes);\n",
        block(spelldefs, "enum class SpellModOp : uint8", "SpellDefines.h", ";"),
        "namespace Trinity { namespace Predicates {\n",
        block(preds_h, "        class TC_GAME_API HealthPctOrderPred", "CommonPredicates.h", ";"),
        "} }\n",
    ]
    position_block = between(pos_h, "    constexpr float GetExactDist2dSq(const float x, const float y) const",
                             "constexpr bool IsInDist(Position const* pos, float dist) const { return GetExactDistSq(pos) < dist * dist; }",
                             "Position.h")
    (OUT_DIR / "tc_chain_position.inc").write_text(position_block, encoding="utf-8")

    bodies = [
        "// GENERATED by tools/tc_target_chain_probe/extract.py from TrinityCore -- do not edit",
        block(pos_cpp, "float Position::NormalizeOrientation(float o)", "Position.cpp"),
        block(obj, "bool WorldObject::_IsWithinDist(WorldObject const* obj, float dist2compare, bool is3D, bool incOwnRadius, bool incTargetRadius) const", "Object.cpp"),
        block(obj, "bool WorldObject::IsWithinDist(WorldObject const* obj, float dist2compare, bool is3D /*= true*/, bool incOwnRadius /*= true*/, bool incTargetRadius /*= true*/) const", "Object.cpp"),
        block(obj, "bool WorldObject::GetDistanceOrder(WorldObject const* obj1, WorldObject const* obj2, bool is3D /* = true */) const", "Object.cpp"),
        "template <class T>\n" + block(player, "void Player::ApplySpellMod(SpellInfo const* spellInfo, SpellModOp op, T& basevalue, Spell* spell /*= nullptr*/) const", "Player.cpp"),
        block(spell, "void Spell::SearchChainTargets(std::list<WorldObject*>& targets, uint32 chainTargets, WorldObject* target, SpellTargetObjectTypes objectType,", "Spell.cpp"),
        "namespace Trinity {\n",
        block(spell_h, "    struct TargetPriorityRule\n", "Spell.h", ";"),
        "TC_GAME_API void SortTargetsWithPriorityRules(std::list<WorldObject*>& targets, size_t maxTargets, std::span<TargetPriorityRule const> rules);\n",
        "template <std::size_t N>\n" + block(spell_h, "    inline void SortTargetsWithPriorityRules(std::list<WorldObject*>& targets, size_t maxTargets, std::array<TargetPriorityRule, N> const& rules)", "Spell.h"),
        block(spell, "void SelectRandomInjuredTargets(std::list<WorldObject*>& targets, size_t maxTargets, bool prioritizePlayers, Unit const* prioritizeGroupMembersOf /*= nullptr*/)", "Spell.cpp"),
        block(spell, "void SortTargetsWithPriorityRules(std::list<WorldObject*>& targets, size_t maxTargets, std::span<TargetPriorityRule const> rules)", "Spell.cpp"),
        "} // namespace Trinity\n",
        block(preds, "bool Trinity::Predicates::HealthPctOrderPred::operator()(WorldObject const* objA, WorldObject const* objB) const", "CommonPredicates.cpp"),
        "struct RadianceRulesHolder {\n",
        block(priest, "    static std::array<Trinity::TargetPriorityRule, 5> GetRadianceRules(Unit const* caster, Unit const* explTarget)", "spell_priest.cpp"),
        "};\n",
    ]
    OUT_DECLS.write_text("\n".join(decls), encoding="utf-8")
    OUT_BODIES.write_text("\n".join(bodies), encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
