// Track D differential probe: chain targeting, smart selection, RNG container helpers.
//
// Trinity's text (tc_chain_*.inc, generated by extract.py) compiled against the
// minimal stubs below.  Reads line-oriented cases from stdin, prints one JSON
// object per case.  Floats cross the boundary as C99 hex literals (%a / strtof).
//
// Stubs (cut points) -- see extract.py docstring:
//   Spell::SearchAreaTargets  -> driver candidate list (order preserved), records radius/source
//   Spell::IsWithinLOS        -> driver table (default clear)
//   WorldObject::HasInArc     -> per-object driver flag
//   Spell::GetMinMaxRange     -> driver value
//   Player::GetSpellModValues -> driver flat/pct
//   Unit::IsInRaidWith, Unit::HasAura, Creature::IsTreatedAsRaidUnit -> driver facts
//   urand / irand / rand32    -> scripted sequences with recording

#include "Define.h"
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <array>
#include <functional>
#include <list>
#include <map>
#include <memory>
#include <set>
#include <span>
#include <sstream>
#include <string>
#include <vector>
#include <iostream>
#include <deque>
#include <stdexcept>

#include "Containers.h"
#include "EnumFlag.h"
#include "Tuples.h"
#include "Types.h"

// ---- scripted RNG (replaces Random.cpp) -------------------------------------
static std::deque<uint32> g_urand;     // values returned by urand/irand, in order
static std::deque<uint32> g_words;     // engine words returned by rand32
static std::vector<std::string> g_log; // "urand(lo,hi)=v" / "rand32=v"

uint32 urand(uint32 min, uint32 max)
{
    if (g_urand.empty())
        throw std::runtime_error("urand: script exhausted");
    uint32 v = g_urand.front();
    g_urand.pop_front();
    if (v < min || v > max)
        throw std::runtime_error("urand: scripted value out of range");
    g_log.push_back("urand(" + std::to_string(min) + "," + std::to_string(max) + ")=" + std::to_string(v));
    return v;
}
int32 irand(int32 min, int32 max) { return int32(urand(uint32(min), uint32(max))); }
uint32 rand32()
{
    if (g_words.empty())
        throw std::runtime_error("rand32: script exhausted");
    uint32 v = g_words.front();
    g_words.pop_front();
    g_log.push_back("rand32=" + std::to_string(v));
    return v;
}
uint32 urandms(uint32, uint32) { throw std::runtime_error("unused"); }
float frand(float, float) { throw std::runtime_error("unused"); }
float rand_norm() { throw std::runtime_error("unused"); }
float rand_chance() { throw std::runtime_error("unused"); }
uint32 urandweighted(size_t, double const*) { throw std::runtime_error("unused"); }
Milliseconds randtime(Milliseconds, Milliseconds) { throw std::runtime_error("unused"); }


#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

class WorldObject;
class Unit;
#include "tc_chain_decls.inc"

// ---- object model stubs -----------------------------------------------------
using ObjectGuid = uint64;
enum TypeId { TYPEID_UNIT = 5, TYPEID_PLAYER = 6, TYPEID_GAMEOBJECT = 8 };
enum SpellDmgClass { SPELL_DAMAGE_CLASS_NONE = 0, SPELL_DAMAGE_CLASS_MAGIC = 1, SPELL_DAMAGE_CLASS_MELEE = 2, SPELL_DAMAGE_CLASS_RANGED = 3 };
enum SpellAttr2 : uint32 { SPELL_ATTR2_CHAIN_FROM_CASTER = 0x1 };
enum SpellAttr5 : uint32 { SPELL_ATTR5_MELEE_CHAIN_TARGETING = 0x1 };
enum SpellTargetObjectTypes { TARGET_OBJECT_TYPE_UNIT = 3 };
enum SpellTargetCheckTypes { TARGET_CHECK_DEFAULT = 0 };
enum : uint32 { SPELL_PRIEST_ATONEMENT_EFFECT = 194384 };
namespace VMAP { enum class ModelIgnoreFlags : uint32 { Nothing = 0, M2 = 1 }; }
namespace Trinity { enum class WorldObjectSpellAreaTargetSearchReason { Area, Chain }; }
struct ConditionContainer {};
struct SpellRange { float Min = 0.0f; float Max = 0.0f; };

struct Position
{
    float m_positionX = 0.0f, m_positionY = 0.0f, m_positionZ = 0.0f, m_orientation = 0.0f;
    float GetPositionX() const { return m_positionX; }
    float GetPositionY() const { return m_positionY; }
    float GetPositionZ() const { return m_positionZ; }
    static float NormalizeOrientation(float o);
#include "tc_chain_position.inc"
};

struct MovementInfo { struct { Position pos; } transport; };
class Unit; class Creature; class Player;

class WorldObject : public Position
{
public:
    virtual ~WorldObject() = default;
    int idx = 0;
    TypeId type = TYPEID_UNIT;
    float reach = 0.0f;
    bool inFront = true;
    MovementInfo m_movementInfo;

    float GetCombatReach() const { return reach; }
    WorldObject* GetTransport() const { return nullptr; }
    bool IsUnit() const { return type != TYPEID_GAMEOBJECT; }
    bool IsPlayer() const { return type == TYPEID_PLAYER; }
    bool IsCreature() const { return type == TYPEID_UNIT; }
    Unit* ToUnit();
    Unit const* ToUnit() const;
    Creature* ToCreature();
    Creature const* ToCreature() const;
    Player* GetSpellModOwner() const;
    bool HasInArc(float /*arc*/, WorldObject const* obj) const { return obj->inFront; }

    bool _IsWithinDist(WorldObject const* obj, float dist2compare, bool is3D, bool incOwnRadius = true, bool incTargetRadius = true) const;
    bool IsWithinDist(WorldObject const* obj, float dist2compare, bool is3D = true, bool incOwnRadius = true, bool incTargetRadius = true) const;
    bool GetDistanceOrder(WorldObject const* obj1, WorldObject const* obj2, bool is3D = true) const;
};

class Unit : public WorldObject
{
public:
    uint64 health = 0, maxHealth = 0;
    std::set<int> raid;          // IsInRaidWith(unit) == raid.count(unit->idx)
    std::set<int> atonementFrom; // HasAura(ATONEMENT_EFFECT, caster) == atonementFrom.count(caster idx)
    uint64 GetHealth() const { return health; }
    uint64 GetMaxHealth() const { return maxHealth; }
    bool IsFullHealth() const { return GetHealth() == GetMaxHealth(); }  // Unit.h:790 (copied)
    bool IsInRaidWith(Unit const* unit) const { return raid.count(unit->idx) != 0; }
    ObjectGuid GetGUID() const { return ObjectGuid(idx); }
    bool HasAura(uint32 spellId, ObjectGuid caster) const
    {
        return spellId == SPELL_PRIEST_ATONEMENT_EFFECT && atonementFrom.count(int(caster)) != 0;
    }
};

class Creature : public Unit
{
public:
    bool raidUnit = false;
    bool IsTreatedAsRaidUnit() const { return raidUnit; }
};

struct SpellInfo;
class Spell;
class Player : public Unit
{
public:
    int32 flat = 0;
    float pct = 1.0f;
    void GetSpellModValues(SpellInfo const*, SpellModOp, Spell*, double, int32* f, float* p) const { *f = flat; *p = pct; }
    template <class T>
    void ApplySpellMod(SpellInfo const* spellInfo, SpellModOp op, T& basevalue, Spell* spell = nullptr) const;
};

static Player* g_modOwner = nullptr;
static std::map<SpellModOp, std::pair<int32, float>> g_mods;

Unit* WorldObject::ToUnit() { return IsUnit() ? static_cast<Unit*>(this) : nullptr; }
Unit const* WorldObject::ToUnit() const { return IsUnit() ? static_cast<Unit const*>(this) : nullptr; }
Creature* WorldObject::ToCreature() { return IsCreature() ? static_cast<Creature*>(this) : nullptr; }
Creature const* WorldObject::ToCreature() const { return IsCreature() ? static_cast<Creature const*>(this) : nullptr; }
Player* WorldObject::GetSpellModOwner() const { return g_modOwner; }

struct SpellInfo
{
    uint32 DmgClass = 0;
    bool chainFromCaster = false;
    bool meleeChain = false;
    bool HasAttribute(SpellAttr2 a) const { return a == SPELL_ATTR2_CHAIN_FROM_CASTER && chainFromCaster; }
    bool HasAttribute(SpellAttr5 a) const { return a == SPELL_ATTR5_MELEE_CHAIN_TARGETING && meleeChain; }
};

struct SpellEffectInfo
{
    EnumFlag<SpellEffectAttributes> EffectAttributes = SpellEffectAttributes::None;
    std::shared_ptr<ConditionContainer> ImplicitTargetConditions;
};

class Spell
{
public:
    SpellInfo const* m_spellInfo = nullptr;
    WorldObject* m_caster = nullptr;
    std::vector<WorldObject*> candidates;
    std::map<std::pair<int, int>, bool> los;
    float minMaxRangeMax = 0.0f;
    float recordedRadius = -1.0f;
    int recordedSource = -1;

    void SearchAreaTargets(std::list<WorldObject*>& targets, SpellEffectInfo const&, SpellRange range, Position const* position,
        WorldObject*, SpellTargetObjectTypes, SpellTargetCheckTypes, ConditionContainer const*,
        Trinity::WorldObjectSpellAreaTargetSearchReason)
    {
        recordedRadius = range.Max;
        recordedSource = static_cast<WorldObject const*>(position)->idx;
        for (WorldObject* c : candidates)
            targets.push_back(c);
    }
    bool IsWithinLOS(WorldObject const* source, WorldObject const* target, bool, VMAP::ModelIgnoreFlags) const
    {
        auto it = los.find({ source->idx, target->idx });
        if (it == los.end())
            it = los.find({ target->idx, source->idx });
        return it == los.end() ? true : it->second;
    }
    SpellRange GetMinMaxRange(bool) const { return { 0.0f, minMaxRangeMax }; }

    void SearchChainTargets(std::list<WorldObject*>& targets, uint32 chainTargets, WorldObject* target, SpellTargetObjectTypes objectType,
        SpellTargetCheckTypes selectType, SpellEffectInfo const& spellEffectInfo, bool isChainHeal);
};

#include "tc_chain_bodies.inc"

// ---- driver ------------------------------------------------------------------
static std::string hexf(float v)
{
    char buf[64];
    std::snprintf(buf, sizeof buf, "%a", double(v));
    return buf;
}

static std::string ids(std::list<WorldObject*> const& l)
{
    std::string s = "[";
    bool first = true;
    for (WorldObject* o : l)
    {
        s += (first ? "" : ",") + std::to_string(o->idx);
        first = false;
    }
    return s + "]";
}

static std::string logJson()
{
    std::string s = "[";
    for (size_t i = 0; i < g_log.size(); ++i)
        s += (i ? ",\"" : "\"") + g_log[i] + "\"";
    return s + "]";
}

static std::vector<std::string> split(std::string const& line)
{
    std::vector<std::string> out;
    std::istringstream in(line);
    std::string w;
    while (in >> w)
        out.push_back(w);
    return out;
}

static float F(std::string const& s) { return std::strtof(s.c_str(), nullptr); }
static uint64 U(std::string const& s) { return std::strtoull(s.c_str(), nullptr, 10); }

struct Logged
{
    int v;
};
static Logged* g_base = nullptr;
static std::vector<std::pair<long, long>> g_swaps;
void swap(Logged& a, Logged& b)
{
    g_swaps.emplace_back(&a - g_base, &b - g_base);
    std::swap(a.v, b.v);
}

// Case formats (one case = lines until "go"):
//   chain <heal> <jumps> <dmgclass> <cfc> <melee> <effattr> <modowner> <jflat> <jpct-hex> <range-hex>
//   shuffle <n> <word>...          resize <n> <size> <draw>...        select <size> <draw>
//   injured <max> <prioPlayers> <groupOf|-1>      rules <max> <explicit|-1> <caster>
//   hpsort <asc>
//   partition <flag>...
// object lines:  obj <idx> <type:5|6|8> <x> <y> <z> <reach> <health> <maxhealth> <infront> <raidunit>
//                raid <idx> <idx...>   aton <idx> <casteridx...>
// order <idx...>  los <a> <b> <0|1>  initial <idx>  words <w...>  go
int main()
{
    std::string line;
    std::vector<std::string> head;
    std::map<int, std::unique_ptr<Creature>> objs;
    std::vector<int> order;
    std::map<std::pair<int, int>, bool> los;
    int initial = -1;
    while (std::getline(std::cin, line))
    {
        auto w = split(line);
        if (w.empty())
            continue;
        if (w[0] == "obj")
        {
            auto o = std::make_unique<Creature>();
            o->idx = std::stoi(w[1]);
            o->type = TypeId(std::stoi(w[2]));
            o->m_positionX = F(w[3]); o->m_positionY = F(w[4]); o->m_positionZ = F(w[5]);
            o->reach = F(w[6]);
            o->health = U(w[7]); o->maxHealth = U(w[8]);
            o->inFront = w[9] == "1";
            o->raidUnit = w[10] == "1";
            objs[o->idx] = std::move(o);
            continue;
        }
        if (w[0] == "raid") { for (size_t i = 2; i < w.size(); ++i) objs.at(std::stoi(w[1]))->raid.insert(std::stoi(w[i])); continue; }
        if (w[0] == "aton") { for (size_t i = 2; i < w.size(); ++i) objs.at(std::stoi(w[1]))->atonementFrom.insert(std::stoi(w[i])); continue; }
        if (w[0] == "order") { for (size_t i = 1; i < w.size(); ++i) order.push_back(std::stoi(w[i])); continue; }
        if (w[0] == "los") { los[{ std::stoi(w[1]), std::stoi(w[2]) }] = w[3] == "1"; continue; }
        if (w[0] == "initial") { initial = std::stoi(w[1]); continue; }
        if (w[0] == "words") { for (size_t i = 1; i < w.size(); ++i) g_words.push_back(uint32(U(w[i]))); continue; }
        if (w[0] == "draws") { for (size_t i = 1; i < w.size(); ++i) g_urand.push_back(uint32(U(w[i]))); continue; }
        if (w[0] != "go") { head = w; continue; }

        std::string out;
        try
        {
            std::string const& cmd = head.at(0);
            if (cmd == "chain")
            {
                SpellInfo si;
                si.DmgClass = uint32(std::stoi(head[3]));
                si.chainFromCaster = head[4] == "1";
                si.meleeChain = head[5] == "1";
                SpellEffectInfo eff;
                eff.EffectAttributes = SpellEffectAttributes(std::stoul(head[6]));
                Player owner;
                owner.flat = std::stoi(head[8]);
                owner.pct = F(head[9]);
                g_modOwner = head[7] == "1" ? &owner : nullptr;
                Spell spell;
                spell.m_spellInfo = &si;
                spell.m_caster = objs.at(0).get();
                spell.minMaxRangeMax = F(head[10]);
                spell.los = los;
                for (int i : order)
                    spell.candidates.push_back(objs.at(i).get());
                std::list<WorldObject*> targets;
                spell.SearchChainTargets(targets, uint32(std::stoul(head[2])), objs.at(initial).get(), TARGET_OBJECT_TYPE_UNIT,
                    TARGET_CHECK_DEFAULT, eff, head[1] == "1");
                out = "{\"targets\":" + ids(targets) + ",\"search_radius\":\"" + hexf(spell.recordedRadius)
                    + "\",\"source\":" + std::to_string(spell.recordedSource) + "}";
                g_modOwner = nullptr;
            }
            else if (cmd == "resize" || cmd == "resize_list")
            {
                size_t n = std::stoul(head[1]);
                int size = std::stoi(head[2]);
                std::list<WorldObject*> tmp;
                std::vector<int> v;
                std::list<int> l;
                for (int i = 0; i < size; ++i) { v.push_back(i); l.push_back(i); }
                std::string kept = "[";
                if (cmd == "resize")
                {
                    Trinity::Containers::RandomResize(v, n);
                    for (size_t i = 0; i < v.size(); ++i) kept += (i ? "," : "") + std::to_string(v[i]);
                }
                else
                {
                    Trinity::Containers::RandomResize(l, n);
                    bool f = true;
                    for (int x : l) { kept += (f ? "" : ",") + std::to_string(x); f = false; }
                }
                out = "{\"kept\":" + kept + "],\"log\":" + logJson() + "}";
            }
            else if (cmd == "select")
            {
                int size = std::stoi(head[1]);
                std::list<int> l;
                for (int i = 0; i < size; ++i) l.push_back(i);
                int const& pick = Trinity::Containers::SelectRandomContainerElement(l);
                out = "{\"pick\":" + std::to_string(pick) + ",\"log\":" + logJson() + "}";
            }
            else if (cmd == "shuffle")
            {
                int n = std::stoi(head[1]);
                std::vector<Logged> v(n);
                for (int i = 0; i < n; ++i) v[i].v = i;
                g_base = v.data();
                g_swaps.clear();
                Trinity::Containers::RandomShuffle(v);
                std::string perm = "[", sw = "[";
                for (int i = 0; i < n; ++i) perm += (i ? "," : "") + std::to_string(v[i].v);
                for (size_t i = 0; i < g_swaps.size(); ++i)
                    sw += (i ? ",[" : "[") + std::to_string(g_swaps[i].first) + "," + std::to_string(g_swaps[i].second) + "]";
                out = "{\"perm\":" + perm + "],\"swaps\":" + sw + "],\"log\":" + logJson() + "}";
            }
            else if (cmd == "injured" || cmd == "rules" || cmd == "hpsort")
            {
                std::list<WorldObject*> targets;
                for (int i : order)
                    targets.push_back(objs.at(i).get());
                if (cmd == "injured")
                {
                    int g = std::stoi(head[3]);
                    Trinity::SelectRandomInjuredTargets(targets, std::stoul(head[1]), head[2] == "1", g < 0 ? nullptr : objs.at(g).get());
                }
                else if (cmd == "rules")
                {
                    int e = std::stoi(head[2]);
                    Unit* expl = e < 0 ? nullptr : objs.at(e).get();
                    Trinity::SortTargetsWithPriorityRules(targets, std::stoul(head[1]), RadianceRulesHolder::GetRadianceRules(objs.at(std::stoi(head[3])).get(), expl));
                }
                else
                    targets.sort(Trinity::Predicates::HealthPctOrderPred(head[1] == "1"));
                out = "{\"targets\":" + ids(targets) + ",\"log\":" + logJson() + "}";
            }
            else if (cmd == "partition")
            {
                std::vector<int> v;
                std::vector<bool> flag;
                for (size_t i = 1; i < head.size(); ++i) { v.push_back(int(i - 1)); flag.push_back(head[i] == "1"); }
                auto it = std::partition(v.begin(), v.end(), [&](int x) { return bool(flag[x]); });
                std::string s = "[";
                for (size_t i = 0; i < v.size(); ++i) s += (i ? "," : "") + std::to_string(v[i]);
                out = "{\"order\":" + s + "],\"split\":" + std::to_string(it - v.begin()) + "}";
            }
            else
                throw std::runtime_error("unknown command " + cmd);
            if (!g_urand.empty())
                throw std::runtime_error("unconsumed urand values");
        }
        catch (std::exception const& e)
        {
            out = std::string("{\"error\":\"") + e.what() + "\",\"log\":" + logJson() + "}";
        }
        if (out.size() && out.back() == '}' && out.find("\"error\"") == std::string::npos)
            out.insert(out.size() - 1, ",\"words_left\":" + std::to_string(g_words.size()));
        std::cout << out << "\n";
        std::cout.flush();
        objs.clear(); order.clear(); los.clear(); initial = -1; head.clear();
        g_urand.clear(); g_words.clear(); g_log.clear();
    }
    return 0;
}
