#!/usr/bin/env python3
"""Extract TrinityCore proc-policy code verbatim into a generated header.

Like ``tools/tc_probe``, the point is that the C++ side of the differential
test is *Trinity's own text*, compiled against minimal stubs, not a retyping.

Extracted (verbatim):
  SharedDefines.h        enum SpellSchools, SpellSchoolMask, SpellAttr0..16,
                         SpellEffects, SpellFamilyNames
  SpellAuraDefines.h     enum AuraType
  DBCEnums.h             enum SpellProcsPerMinuteModType
  SpellMgr.h             ProcFlags ... PROC_ATTR_ALL_ALLOWED, struct SpellProcEntry
  SpellDefines.h         class ProcFlagsInit
  Util.h                 RoundToInterval
  SpellMgr.cpp           SpellMgr::CanSpellTriggerProcOnEvent
                         the default-generation block of SpellMgr::LoadSpellProcs
  SpellInfo.cpp          SpellEffectInfo::IsEffect/IsAura/IsAreaAuraEffect/
                         IsUnitOwnedAuraEffect, SpellInfo::IsAffected,
                         CalcPPMHasteMod, CalcPPMCritMod, CalcPPMItemLevelMod,
                         SpellInfo::CalcProcPPM
  SpellAuras.cpp         Aura::CalcProcChance, Aura::CalcPPMProcChance
  Unit.cpp               Unit::GetPPMProcChance, Unit::GetWeaponProcChance
  Unit.h                 Unit::GetClassMask (inline)
Included directly (not extracted): EnumFlag.h, FlagsArray.h, Duration.h, RaceMask.h.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

WORKSPACE_PARENT = Path(__file__).resolve().parents[4].parent
TC_ROOT = Path(sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] else WORKSPACE_PARENT / "TrinityCore")
OUT_DIR = Path(sys.argv[2] if len(sys.argv) > 2 else Path(__file__).parent)
OUT_DECLS = OUT_DIR / "tc_proc_decls.inc"
OUT_BODIES = OUT_DIR / "tc_proc_bodies.inc"
G = TC_ROOT / "src/server/game"


def read(rel: str) -> str:
    return (G / rel).read_text(encoding="utf-8")


def braced(text: str, start: int) -> tuple[int, int]:
    open_brace = text.index("{", start)
    depth = 0
    for pos in range(open_brace, len(text)):
        if text[pos] == "{":
            depth += 1
        elif text[pos] == "}":
            depth -= 1
            if depth == 0:
                return open_brace, pos + 1
    raise SystemExit("unbalanced braces")


def enum_block(text: str, header: str) -> str:
    start = text.index(header)
    _, end = braced(text, start)
    return text[start:end] + ";"


def body(text: str, signature: str) -> str:
    start = text.find(signature)
    if start < 0:
        raise SystemExit(f"signature not found: {signature}")
    a, b = braced(text, start)
    return text[a:b]


def between(text: str, first: str, last: str) -> str:
    a = text.index(first)
    b = text.index(last, a) + len(last)
    return text[a:b]


def main() -> int:
    shared = read("Miscellaneous/SharedDefines.h")
    auras = read("Spells/Auras/SpellAuraDefines.h")
    dbc = read("DataStores/DBCEnums.h")
    mgr_h = read("Spells/SpellMgr.h")
    defines = read("Spells/SpellDefines.h")
    mgr = read("Spells/SpellMgr.cpp")
    info = read("Spells/SpellInfo.cpp")
    spell_auras = read("Spells/Auras/SpellAuras.cpp")
    unit = read("Entities/Unit/Unit.cpp")
    unit_h = read("Entities/Unit/Unit.h")
    util = (TC_ROOT / "src/common/Utilities/Util.h").read_text(encoding="utf-8")

    parts = ["// GENERATED by extract.py -- do not edit.", f"// TrinityCore: {TC_ROOT}", ""]
    parts.append(enum_block(shared, "enum SpellSchools : uint16"))
    parts.append(enum_block(shared, "enum SpellSchoolMask : uint32"))
    for i in range(17):
        parts.append(enum_block(shared, f"enum SpellAttr{i} : uint32"))
    parts.append(enum_block(shared, "enum SpellEffects\n"))
    parts.append(enum_block(shared, "enum SpellFamilyNames : uint8"))
    parts.append(enum_block(auras, "enum AuraType : uint32"))
    parts.append(enum_block(dbc, "enum SpellProcsPerMinuteModType"))

    procs = between(mgr_h, "enum ProcFlags : uint32", "PROC_ATTR_CANT_PROC_FROM_ITEM_CAST)")
    parts.append(procs)
    parts.append(between(defines, "class ProcFlagsInit : public FlagsArray<int32, 2>", "\n};") )
    parts.append(between(mgr_h, "struct SpellProcEntry\n{", "\n};"))
    rti = between(util, "template <class T>\ninline T RoundToInterval", "\n}")
    parts.append(rti)

    header = parts[:3]
    OUT_DECLS.write_text("\n\n".join(parts) + "\n", encoding="utf-8")
    parts = list(header)

    # SpellEffectInfo / SpellInfo helpers
    for sig in ("bool SpellEffectInfo::IsEffect() const", "bool SpellEffectInfo::IsAura() const",
                "bool SpellEffectInfo::IsAreaAuraEffect() const",
                "bool SpellEffectInfo::IsUnitOwnedAuraEffect() const",
                "bool SpellInfo::IsAffected(uint32 familyName, flag128 const& familyFlags) const"):
        parts.append(sig + "\n" + body(info, sig))
    for sig in ("inline float CalcPPMHasteMod(SpellProcsPerMinuteModEntry const* mod, Unit* caster)",
                "inline float CalcPPMCritMod(SpellProcsPerMinuteModEntry const* mod, Unit* caster)",
                "inline float CalcPPMItemLevelMod(SpellProcsPerMinuteModEntry const* mod, int32 itemLevel)",
                "float SpellInfo::CalcProcPPM(Unit* caster, int32 itemLevel) const"):
        parts.append(sig + "\n" + body(info, sig))

    parts.append("bool SpellMgr::CanSpellTriggerProcOnEvent(SpellProcEntry const& procEntry, ProcEventInfo& eventInfo)\n"
                 + body(mgr, "bool SpellMgr::CanSpellTriggerProcOnEvent("))
    gen = between(mgr, "    bool isTriggerAura[TOTAL_AURAS];", "    mSpellProcMap.merge(generatedSpellProcMap);")
    parts.append("void SpellMgr::GenerateDefaultProcs()\n{\n    uint32 count = 0;\n    uint32 oldMSTime = 0;\n"
                 + gen + "\n}")

    for sig in ("float Aura::CalcProcChance(SpellProcEntry const& procEntry, ProcEventInfo& eventInfo) const",
                "float Aura::CalcPPMProcChance(Unit* actor) const"):
        parts.append(sig + "\n" + body(spell_auras, sig))
    for sig in ("float Unit::GetPPMProcChance(uint32 WeaponSpeed, float PPM, SpellInfo const* spellProto) const",
                "float Unit::GetWeaponProcChance() const"):
        parts.append(sig + "\n" + body(unit, sig))
    m = re.search(r"uint32 GetClassMask\(\) const \{[^}]*\}", unit_h)
    parts.append("inline uint32 Unit::" + m.group(0)[len("uint32 "):])
    OUT_BODIES.write_text("\n\n".join(parts) + "\n", encoding="utf-8")
    print(f"wrote {OUT_DECLS} and {OUT_BODIES}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
