#!/usr/bin/env python3
"""Extract TrinityCore aura stack/charge code verbatim (aura-lifecycle Track C).

The C++ side of the differential for ``aura_lifecycle/stacks.py`` + ``charges.py`` is
Trinity's own text compiled against minimal stubs (``probe.cpp``).

Extracted verbatim (TrinityCore @ 7f3d43b):
  SpellAuras.cpp  Aura::SetDuration, RefreshDuration, RefreshTimers, SetCharges, CalcMaxCharges, ModCharges,
                  SetStackAmount, IsUsingStacks, CalcMaxStackAmount, ModStackAmount, PrepareProcChargeDrop,
                  ConsumeProcCharges, and the charge statements of the Aura constructor
  SpellAuras.h    AuraCreateInfo::SetStackAmount
  Unit.cpp        Unit::_TryStackingOrRefreshingExistingAura (the refresh branch of TryRefreshStackOrCreate)
  SpellInfo.cpp   SpellInfo::IsPassive, IsChanneled, IsMultiSlotAura, IsStackableOnOneSlotWithDifferentCasters
  Spell.cpp       the ResetPeriodicTimer statement of Spell::DoSpellEffectHit
  Player.cpp      Player::ApplySpellMod<T> (arithmetic; GetSpellModValues is a driver cut point)
  enums           SpellAttr0..13, SpellCustomAttributes, TriggerCastFlags, SpellModOp, AuraRemoveMode,
                  ProcAttributes, SpellEffectAttributes, TimeConstants
"""

from __future__ import annotations

import sys
from pathlib import Path

WORKSPACE_PARENT = Path(__file__).resolve().parents[5]
TC_ROOT = Path(sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] else WORKSPACE_PARENT / "TrinityCore")
OUT_DIR = Path(sys.argv[2] if len(sys.argv) > 2 else Path(__file__).parent)
OUT_DECLS = OUT_DIR / "tc_stack_decls.inc"
OUT_BODIES = OUT_DIR / "tc_stack_bodies.inc"
OUT_CREATEINFO = OUT_DIR / "tc_stack_createinfo.inc"
G = TC_ROOT / "src/server/game"


def braced(text: str, start: int) -> tuple[int, int]:
    open_brace = text.index("{", start)
    depth = 0
    for pos in range(open_brace, len(text)):
        if text[pos] == "{":
            depth += 1
        elif text[pos] == "}":
            depth -= 1
            if depth == 0:
                return open_brace, pos + 1
    raise SystemExit("unbalanced braces")


def function(text: str, signature: str, source: str, prefix: str = "") -> str:
    start = text.find(signature)
    if start < 0:
        raise SystemExit(f"signature not found in {source}: {signature}")
    if text.find(signature, start + 1) >= 0:
        raise SystemExit(f"signature not unique in {source}: {signature}")
    line = text.count("\n", 0, start) + 1
    _, b = braced(text, start)
    return f"// {source}:{line}\n{prefix}{text[start:b]}\n"


def enum_block(text: str, head: str, source: str) -> str:
    start = text.index(head)
    end = text.index("};", start) + 2
    line = text.count("\n", 0, start) + 1
    return f"// {source}:{line}\n{text[start:end]}"


def statement(text: str, first: str, last: str, source: str) -> str:
    a = text.index(first)
    if text.find(first, a + 1) >= 0:
        raise SystemExit(f"statement anchor not unique in {source}: {first}")
    b = text.index(last, a) + len(last)
    line = text.count("\n", 0, a) + 1
    return f"// {source}:{line}\n{text[a:b]}\n"


def line_of(text: str, first: str, source: str) -> str:
    a = text.index(first)
    b = text.index("\n", a)
    line = text.count("\n", 0, a) + 1
    return f"// {source}:{line}\n{text[a:b]}\n"


def main() -> int:
    auras_cpp = (G / "Spells/Auras/SpellAuras.cpp").read_text(encoding="utf-8")
    auras_h = (G / "Spells/Auras/SpellAuras.h").read_text(encoding="utf-8")
    aura_defs = (G / "Spells/Auras/SpellAuraDefines.h").read_text(encoding="utf-8")
    unit_cpp = (G / "Entities/Unit/Unit.cpp").read_text(encoding="utf-8")
    info_cpp = (G / "Spells/SpellInfo.cpp").read_text(encoding="utf-8")
    info_h = (G / "Spells/SpellInfo.h").read_text(encoding="utf-8")
    spell_cpp = (G / "Spells/Spell.cpp").read_text(encoding="utf-8")
    spell_defs = (G / "Spells/SpellDefines.h").read_text(encoding="utf-8")
    spellmgr_h = (G / "Spells/SpellMgr.h").read_text(encoding="utf-8")
    player_cpp = (G / "Entities/Player/Player.cpp").read_text(encoding="utf-8")
    shared = (G / "Miscellaneous/SharedDefines.h").read_text(encoding="utf-8")
    dbc = (G / "DataStores/DBCEnums.h").read_text(encoding="utf-8")
    common = (TC_ROOT / "src/common/Common.h").read_text(encoding="utf-8")

    decls = ["// GENERATED by tools/tc_aura_stack_probe/extract.py from TrinityCore -- do not edit",
             enum_block(common, "enum TimeConstants", "Common.h")]
    for n in range(14):
        decls.append(enum_block(shared, f"enum SpellAttr{n} : uint32", "SharedDefines.h"))
    decls += [
        enum_block(info_h, "enum SpellCustomAttributes", "SpellInfo.h"),
        enum_block(spell_defs, "enum TriggerCastFlags : uint32", "SpellDefines.h"),
        enum_block(spell_defs, "enum class SpellModOp : uint8", "SpellDefines.h"),
        enum_block(aura_defs, "enum AuraRemoveMode", "SpellAuraDefines.h"),
        enum_block(spellmgr_h, "enum ProcAttributes : uint32", "SpellMgr.h"),
        enum_block(dbc, "enum class SpellEffectAttributes", "DBCEnums.h"),
    ]

    bodies = ["// GENERATED by tools/tc_aura_stack_probe/extract.py from TrinityCore -- do not edit"]
    for sig in ("bool SpellInfo::IsPassive() const",
                "bool SpellInfo::IsChanneled() const",
                "bool SpellInfo::IsMultiSlotAura() const",
                "bool SpellInfo::IsStackableOnOneSlotWithDifferentCasters() const"):
        bodies.append(function(info_cpp, sig, "SpellInfo.cpp"))
    bodies.append(function(player_cpp,
                           "void Player::ApplySpellMod(SpellInfo const* spellInfo, SpellModOp op, T& basevalue, Spell* spell /*= nullptr*/) const",
                           "Player.cpp", prefix="template <class T>\n"))
    for sig in ("void Aura::SetDuration(int32 duration, bool withMods)",
                "void Aura::RefreshDuration(bool withMods)",
                "void Aura::RefreshTimers(bool resetPeriodicTimer)",
                "void Aura::SetCharges(uint8 charges)",
                "uint8 Aura::CalcMaxCharges(Unit* caster) const",
                "bool Aura::ModCharges(int32 num, AuraRemoveMode removeMode)",
                "void Aura::SetStackAmount(uint8 stackAmount)",
                "bool Aura::IsUsingStacks() const",
                "uint32 Aura::CalcMaxStackAmount() const",
                "bool Aura::ModStackAmount(int32 num, AuraRemoveMode removeMode /*= AURA_REMOVE_BY_DEFAULT*/, bool resetPeriodicTimer /*= true*/)",
                "void Aura::PrepareProcChargeDrop(SpellProcEntry const* procEntry, ProcEventInfo const& eventInfo)",
                "void Aura::ConsumeProcCharges(SpellProcEntry const* procEntry)"):
        bodies.append(function(auras_cpp, sig, "SpellAuras.cpp"))
    ctor = statement(auras_cpp, "    m_procCharges = CalcMaxCharges(createInfo.Caster);", "m_procCharges != 0;", "SpellAuras.cpp")
    bodies.append("void Aura::ProbeCtorCharges(AuraCreateInfo const& createInfo)\n{\n" + ctor + "}\n")
    bodies.append(function(unit_cpp, "Aura* Unit::_TryStackingOrRefreshingExistingAura(AuraCreateInfo& createInfo)", "Unit.cpp"))
    reset = statement(spell_cpp, "                bool const resetPeriodicTimer = ", ";", "Spell.cpp")
    bodies.append("bool ProbeResetPeriodicOnHit(SpellInfo const* m_spellInfo, uint32 _triggeredCastFlags)\n{\n"
                  + reset + "    return resetPeriodicTimer;\n}\n")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_DECLS.write_text("\n\n".join(decls) + "\n", encoding="utf-8")
    OUT_BODIES.write_text("\n\n".join(bodies) + "\n", encoding="utf-8")
    OUT_CREATEINFO.write_text(line_of(auras_h, "    AuraCreateInfo& SetStackAmount(int32 stackAmount)", "SpellAuras.h"),
                              encoding="utf-8")
    print(f"wrote {OUT_DECLS.name} ({len(decls)}), {OUT_BODIES.name} ({len(bodies)}), {OUT_CREATEINFO.name} from {TC_ROOT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
