"""Synthetic differential fixtures, the fixtures index and corpus regeneration.

The fixtures are *synthetic*: no real character was exported.  Every id is
nevertheless source-valid for the pinned snapshot:

* trait entries come from the spec's authored starter build (the newest
  ``TraitTreeLoadout`` row on the class trait tree), replayed step by step and
  kept only while valid at the fixture level, plus the lowest-id selectable
  hero sub-tree filled greedily (see ``starter_traits``);
* items come from ``docs/research/gearing-corpora/current-gear-corpus.json``
  (real ItemIDs, corpus contexts).  The current-gear corpus carries no class
  tier set (its loot relationship is JournalEncounterItem; tier pieces come
  from tokens), so the 4-piece fixtures take their tier pieces from
  ``ItemSet``/``ItemSparse`` rows of the current expansion, the same pieces the
  charstats proof corpus (``charstats-corpora/gear-to-character-proof.json``)
  already uses -- labelled in each fixture's provenance notes;
* gems and enchants are current-expansion ``ItemSparse.Gem_properties`` items
  and enchant-scroll ``SpellItemEnchantment`` ids; the socket comes from the
  pure socket bonus list 12234 (an explicit bonus-list identity input).

Nothing here is a simulator answer; the compiled outputs are regenerated by
``character_prep.py compile-all``.
"""

from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path
from typing import Any

from . import CORPORA, ROOT, SNAPSHOT_BUILD, SourceError
from .compiler import (
    FIXTURES_DIR,
    Compiler,
    Snapshot,
    TraitEngine,
    compile_all,
)
from .fixture import FIXTURE_VERSION, Fixture, canonical_json

GEAR_CORPUS = ROOT / "docs" / "research" / "gearing-corpora" / "current-gear-corpus.json"
SOCKET_BONUS_LIST = 12234          # ItemBonus type 6 only; highest-id pure socket list in the snapshot
GEM_DEADLY_PERIDOT = 240857        # ItemSparse.Gem_properties -> enchant 8114 (+Haste & +Crit)
GEM_MASTERFUL_AMETHYST = 240863    # -> enchant 8126 (+Mastery)
ENCHANT_ARMOR_KIT = 8158           # Forest Hunter's Armor Kit (Agi/Str + Stamina)
ENCHANT_SPELLTHREAD = 7934         # Sunfire Silk Spellthread (Int + Stamina)
ENCHANT_WEAPON = 8055              # Smuggler's Enchanted Edge
ENCHANT_CLOAK = 8042               # Illusory Adornment - Blooming Light
MP_CONTEXT = 16                    # MythicPlus_End_of_Run
MP_KEY = 10
RAID_CONTEXT = 6                   # Raid_Mythic
TIER_CONTEXT = 6
ARMOR = {"cloth": 1, "leather": 2, "mail": 3, "plate": 4}
#: ItemSparse.ExpansionID of the current season's items.  The M+ rotation also lists legacy dungeon items
#: (ExpansionID 7 / 9) whose gearing-resolved context-16 item level is 59 / 250; fixtures use current items only.
CURRENT_EXPANSION_ID = 11
#: Fixture level.  Every current-season item resolves to a required level of 90 (ItemBonus type 49
#: SCALING_CONFIG_AND_REQ_LEVEL -> ItemScalingConfig.RequiredLevel 90, Item.cpp:3143-3163; Item::GetRequiredLevel
#: Item.cpp:2864-2874), and Player::CanUseItem refuses it below that level (Player.cpp:11148-11149), so the synthetic
#: characters are level 90 (MaxPlayerLevel, World.cpp:750).  player_classlevelstats stops at 80, so the fixtures opt
#: into Trinity's base-stat gap fill explicitly (server_inputs.base_stats.fill_rule = trinity); one variant does not.
FIXTURE_LEVEL = 90
ARMOR_SLOT_INVTYPE = {"HEAD": (1,), "SHOULDERS": (3,), "CHEST": (5, 20), "WAIST": (6,), "LEGS": (7,), "FEET": (8,),
                      "WRISTS": (9,), "HANDS": (10,), "BACK": (16,)}

#: (name, race, class, spec, armour, weapons {slot: item}, extras)
FIXTURE_PLAN: list[dict[str, Any]] = [
    {"name": "arms-warrior-plate-2h", "race": 1, "class": 1, "spec": 71, "armor": "plate",
     "weapons": {"MAINHAND": 268213}, "trinket1": 270173, "pvp": [{"pvp_talent_id": 34, "slot": 0}],
     "enchants": {"MAINHAND": [ENCHANT_WEAPON], "LEGS": [ENCHANT_ARMOR_KIT], "BACK": [ENCHANT_CLOAK]},
     "gem": GEM_DEADLY_PERIDOT, "notes": ["plate 2H; ItemSet 2070 2-piece (2H + trinket) from the current-gear corpus",
                                          "pvp_traits present and enabled (PvpTalent 34, slot 0)"]},
    {"name": "fury-warrior-plate-titan-grip", "race": 2, "class": 1, "spec": 72, "armor": "plate", "prefer": "mythic_plus",
     "weapons": {"MAINHAND": 268213, "OFFHAND": 268215}, "enchants": {"MAINHAND": [ENCHANT_WEAPON], "OFFHAND": [ENCHANT_WEAPON]},
     "gem": GEM_DEADLY_PERIDOT, "notes": ["two 2H weapons: exercises the Titan's Grip off-hand gate (Player::FindEquipSlot :9261)"]},
    {"name": "frost-dk-plate-dw-tier4", "race": 5, "class": 6, "spec": 251, "armor": "plate",
     "weapons": {"MAINHAND": 268206, "OFFHAND": 268210}, "tier": [271474, 271472, 271477, 271473],
     "enchants": {"MAINHAND": [ENCHANT_WEAPON], "OFFHAND": [ENCHANT_WEAPON], "LEGS": [ENCHANT_ARMOR_KIT]},
     "gem": GEM_MASTERFUL_AMETHYST,
     "notes": ["plate dual wield (SpecializationSpells 674 Dual Wield for spec 251)",
               "ItemSet 2055 4 pieces (tier pieces are absent from the current-gear corpus; ids from ItemSet/ItemSparse "
               "as used by charstats-corpora/gear-to-character-proof.json)"]},
    {"name": "bm-hunter-mail-ranged-pet", "race": 3, "class": 3, "spec": 253, "armor": "mail",
     "weapons": {"MAINHAND": 268207}, "enchants": {"LEGS": [ENCHANT_ARMOR_KIT], "BACK": [ENCHANT_CLOAK]},
     "gem": GEM_DEADLY_PERIDOT,
     "controlled_units": {"hunter_pet": {"creature_family_id": 1, "pet_specialization_id": 74,
                                         "note": "identity inputs for the hunter pet (CreatureFamily 1, pet ChrSpecialization 74); "
                                                 "creature entry / level facts are Track A's"}},
     "notes": ["mail ranged (INVTYPE_RANGED in MAINHAND, Player.cpp:9256); controlled_units.hunter_pet section present"]},
    {"name": "enhancement-shaman-mail-dw", "race": 8, "class": 7, "spec": 263, "armor": "mail", "prefer": "mythic_plus",
     "weapons": {"MAINHAND": 268209, "OFFHAND": 273780}, "trinket1": 270173,
     "enchants": {"MAINHAND": [ENCHANT_WEAPON], "OFFHAND": [ENCHANT_WEAPON]}, "gem": GEM_MASTERFUL_AMETHYST,
     "notes": ["mail dual wield (SpecializationSpells 86629); ItemSet 2070 2-piece via WEAPONMAINHAND + trinket"]},
    {"name": "subtlety-rogue-leather-dw", "race": 4, "class": 4, "spec": 261, "armor": "leather", "prefer": "mythic_plus",
     "weapons": {"MAINHAND": 251128, "OFFHAND": 251180},
     "enchants": {"MAINHAND": [ENCHANT_WEAPON], "OFFHAND": [ENCHANT_WEAPON], "LEGS": [ENCHANT_ARMOR_KIT]},
     "gem": GEM_DEADLY_PERIDOT,
     "notes": ["leather agility dual wield; Dual Wield 674 reaches rogues through the class skill line (SkillLineAbility), "
               "so options.include_class_skill_lines must stay true for the off-hand gate"]},
    {"name": "balance-druid-leather-caster", "race": 6, "class": 11, "spec": 102, "armor": "leather",
     "weapons": {"MAINHAND": 268199}, "enchants": {"MAINHAND": [ENCHANT_WEAPON], "LEGS": [ENCHANT_SPELLTHREAD]},
     "gem": GEM_MASTERFUL_AMETHYST, "notes": ["leather caster with forms; starter build carries multi-rank nodes"]},
    {"name": "demonology-warlock-cloth-pet", "race": 10, "class": 9, "spec": 266, "armor": "cloth",
     "weapons": {"MAINHAND": 268202, "OFFHAND": 268197}, "enchants": {"MAINHAND": [ENCHANT_WEAPON], "LEGS": [ENCHANT_SPELLTHREAD]},
     "gem": GEM_MASTERFUL_AMETHYST,
     "controlled_units": {"active_demon": {"summon_spell_id": 30146,
                                           "note": "identity input: the demon summoned before the pull (Summon Felguard); Track A owns the rest"}},
     "notes": ["cloth pet class; MAINHAND one-hand + INVTYPE_HOLDABLE off-hand (Player.cpp:9273)"]},
    {"name": "holy-priest-cloth-healer-tier4", "race": 11, "class": 5, "spec": 257, "armor": "cloth",
     "weapons": {"MAINHAND": 268199}, "tier": [271555, 271553, 271554, 271556],
     "enchants": {"MAINHAND": [ENCHANT_WEAPON], "LEGS": [ENCHANT_SPELLTHREAD], "BACK": [ENCHANT_CLOAK]},
     "gem": GEM_MASTERFUL_AMETHYST,
     "notes": ["cloth healer; ItemSet 2063 4 pieces (see frost-dk note on tier sources)"]},
    {"name": "windwalker-monk-leather-dw-tier4", "race": 24, "class": 10, "spec": 269, "armor": "leather", "prefer": "mythic_plus",
     "weapons": {"MAINHAND": 270930, "OFFHAND": 251186}, "tier": [271519, 271517, 271522, 271518],
     "enchants": {"MAINHAND": [ENCHANT_WEAPON], "OFFHAND": [ENCHANT_WEAPON]}, "gem": GEM_DEADLY_PERIDOT,
     "notes": ["leather fist-weapon dual wield (SpecializationSpells 124146); ItemSet 2061 4 pieces"]},
    {"name": "arms-warrior-plate-dw-learned", "race": 1, "class": 1, "spec": 71, "armor": "plate",
     "weapons": {"MAINHAND": 268206, "OFFHAND": 268210}, "learned_spells": [296087],
     "enchants": {"MAINHAND": [ENCHANT_WEAPON], "OFFHAND": [ENCHANT_WEAPON]}, "gem": GEM_DEADLY_PERIDOT,
     "notes": ["one-hand dual wield for Arms: spell 296087 'Dual Wield' sits on SkillLineAbility 40461 (Warrior class line "
               "840, AcquireMethod 0 Learned), which Player::LearnSkillRewardedSpells never teaches (Player.cpp:25416-25417); "
               "it is supplied as learned_spells (character state). Without it the OFFHAND gate fails (test)"]},
]


# ---------------------------------------------------------------------------
# corpus item pools
# ---------------------------------------------------------------------------

def _corpus_pools(snapshot: Snapshot) -> dict[str, Any]:
    if not GEAR_CORPUS.exists():
        raise SourceError(f"missing {GEAR_CORPUS}")
    corpus = json.loads(GEAR_CORPUS.read_text(encoding="utf-8"))
    pools: dict[tuple[str, int, int], list[int]] = defaultdict(list)   # (kind, class, subclass) -> ids
    by_inv: dict[tuple[str, int], list[int]] = defaultdict(list)
    seen: set[int] = set()
    expansion = {r[0]: r[1] for r in snapshot.source.project("ItemSparse", ("ID", "ExpansionID"))}
    for kind in ("raid", "mythic_plus"):
        for item in corpus[kind]["items"]:
            iid = int(item["item_id"])
            if iid in seen or not item["variants"] or expansion.get(iid) != CURRENT_EXPANSION_ID:
                continue
            seen.add(iid)
            proto = snapshot.gear.items.get(iid)
            pools[(kind, proto.class_id, proto.subclass_id)].append(iid)
            by_inv[(kind, proto.inventory_type)].append(iid)
    return {"pools": {k: sorted(v) for k, v in pools.items()}, "by_inv": {k: sorted(v) for k, v in by_inv.items()},
            "ids": seen, "window": corpus["window"]}


def _pick(snapshot: Snapshot, pools: dict[str, Any], kind: str, armor_subclass: int, inv_types: tuple[int, ...],
          exclude: set[int]) -> int | None:
    for iid in pools["pools"].get((kind, 4, armor_subclass), []):
        proto = snapshot.gear.items.get(iid)
        if proto.inventory_type in inv_types and iid not in exclude:
            return iid
    return None


def _pick_inv(pools: dict[str, Any], kind: str, inv: int, exclude: set[int]) -> int | None:
    for iid in pools["by_inv"].get((kind, inv), []):
        if iid not in exclude:
            return iid
    return None


def _entry(snapshot: Snapshot, pools: dict[str, Any], item_id: int, *, extra_bonus: list[int] = (), gems: list[int] = (),
           enchants: list[int] = (), tier: bool = False) -> dict[str, Any]:
    proto = snapshot.gear.items.get(item_id)
    entry: dict[str, Any] = {"item_id": item_id}
    in_raid = item_id in pools["by_inv"].get(("raid", proto.inventory_type), [])
    if tier:
        entry["context"] = TIER_CONTEXT
        entry["label"] = "tier piece (ItemSet/ItemSparse; not in current-gear corpus)"
    elif in_raid:
        entry["context"] = RAID_CONTEXT
    else:
        entry["context"] = MP_CONTEXT
        entry["mythic_plus_keystone_level"] = MP_KEY
    if extra_bonus:
        entry["bonus_list_ids"] = list(extra_bonus)
    if gems:
        entry["gems"] = list(gems)
    if enchants:
        entry["enchant_ids"] = list(enchants)
    return entry


# ---------------------------------------------------------------------------
# traits from the authored starter build
# ---------------------------------------------------------------------------

def _config_ok(compiler: Compiler, class_id: int, spec_id: int, level: int, ranks: dict[int, int], hero: int | None) -> bool:
    cfg = compiler.trait_config(spec_id, class_id, level, sorted(ranks.items()), hero, simulate_load_path=False)
    return not cfg["errors"] and not cfg["strict"] and all(r["ok"] for r in cfg["currencies"])


def starter_traits(compiler: Compiler, class_id: int, spec_id: int, level: int = FIXTURE_LEVEL
                   ) -> tuple[list[dict[str, int]], int | None, int, list[str]]:
    """(entries, hero_subtree_id, loadout_id, notes): the authored starter build replayed step by step.

    ``TraitTreeLoadoutEntry.NumPoints`` is the cumulative rank at each ``OrderIndex`` step and the authored builds
    spend the level-90 budget, so each step is kept only while the whole config stays valid for ``level``
    (TraitMgr::ValidateConfig port + owned currency).  Saved ranks exclude granted ranks (Player.cpp:28533-28550).
    The hero sub-tree is the lowest-id sub-tree the spec may select; its nodes are added greedily (lowest node id,
    first entry, full rank) while the config stays valid.  Synthetic choices, labelled in the notes.
    """
    snap = compiler.snap
    t = snap.traits
    trees, _ = snap.class_trait_trees(class_id)
    loadouts = [(lid, tree) for lid, tree in t["loadouts"].get(spec_id, []) if tree in trees]
    if not loadouts:
        raise SourceError(f"spec {spec_id} has no TraitTreeLoadout on its class trees {trees}")
    lid, tree = max(loadouts)
    notes: list[str] = []
    others = sorted({tr for _, tr in t["loadouts"].get(spec_id, []) if tr not in trees})
    if others:
        notes.append(f"spec {spec_id} also has TraitTreeLoadout rows on trees {others}, which Trinity never loads for class "
                     f"{class_id} (class trees {trees}); ignored")
    engine = TraitEngine(t, spec_id, class_id, level, trees)
    granted = {g["entry"]: g["granted"] for g in engine.granted_entries()}
    ranks: dict[int, int] = {}
    kept = skipped = 0
    for row in sorted(t["loadout_entries"].get(lid, []), key=lambda r: r["order"]):
        entry_id = row["entry"]
        if not entry_id:
            cands = t["node_entries"].get(row["node"], [])
            if len(cands) != 1:
                skipped += 1
                continue
            entry_id = cands[0]
        target = row["points"] - granted.get(entry_id, 0)
        if target <= ranks.get(entry_id, 0):
            continue
        trial = dict(ranks)
        trial[entry_id] = target
        if _config_ok(compiler, class_id, spec_id, level, trial, None):
            ranks = trial
            kept += 1
        else:
            skipped += 1
    notes.append(f"starter build TraitTreeLoadout {lid} (tree {tree}) replayed in OrderIndex order at level {level}: "
                 f"{kept} steps kept, {skipped} steps skipped (invalid or over budget at this level; the authored build "
                 f"spends the level-90 budget)")

    hero = None
    for st_id, st in sorted(t["subtree"].items()):
        if st["tree"] in trees and _config_ok(compiler, class_id, spec_id, level, ranks, st_id):
            hero = st_id
            break
    if hero is None:
        notes.append("no selectable hero sub-tree at this level")
    else:
        added = 0
        hero_nodes = sorted(n for n in t["tree_nodes"].get(t["subtree"][hero]["tree"], []) if t["node"][n]["subtree"] == hero)
        changed = True
        while changed:
            changed = False
            for node_id in hero_nodes:
                node_entries = t["node_entries"].get(node_id, [])
                if any(e in ranks for e in node_entries):
                    continue
                for e in node_entries:
                    target = t["entry"][e]["max_ranks"] - granted.get(e, 0)
                    if target <= 0:
                        continue
                    trial = dict(ranks)
                    trial[e] = target
                    if _config_ok(compiler, class_id, spec_id, level, trial, hero):
                        ranks = trial
                        added += 1
                        changed = True
                        break
        notes.append(f"hero sub-tree {hero} ({t['subtree'][hero]['name']}): lowest selectable sub-tree id; {added} nodes "
                     f"added greedily (lowest node id, first valid entry, full rank); granted entry nodes excluded")
    out = [{"node_entry_id": e, "rank": r} for e, r in sorted(ranks.items())]
    return out, hero, lid, notes


# ---------------------------------------------------------------------------
# fixtures
# ---------------------------------------------------------------------------

def build_fixture(compiler: Compiler, plan: dict[str, Any], pools: dict[str, Any]) -> dict[str, Any]:
    snapshot = compiler.snap
    entries, hero, loadout_id, notes = starter_traits(compiler, plan["class"], plan["spec"], FIXTURE_LEVEL)
    armor = ARMOR[plan["armor"]]
    prefer = plan.get("prefer", "raid")
    other = "mythic_plus" if prefer == "raid" else "raid"
    used: set[int] = set(plan["weapons"].values()) | set(plan.get("tier", []))
    equipment: dict[str, dict[str, Any]] = {}
    tier_slots: dict[str, int] = {}
    for iid in plan.get("tier", []):
        proto = snapshot.gear.items.get(iid)
        for slot, invs in ARMOR_SLOT_INVTYPE.items():
            if proto.inventory_type in invs and slot not in tier_slots:
                tier_slots[slot] = iid
                break
    for slot, invs in ARMOR_SLOT_INVTYPE.items():
        if slot in tier_slots:
            equipment[slot] = _entry(snapshot, pools, tier_slots[slot], tier=True,
                                     enchants=plan.get("enchants", {}).get(slot, ()))
            continue
        iid = _pick(snapshot, pools, prefer, armor, invs, used) or _pick(snapshot, pools, other, armor, invs, used)
        if iid is None and slot == "BACK":
            iid = _pick(snapshot, pools, prefer, 1, invs, used) or _pick(snapshot, pools, other, 1, invs, used)
        if iid is None:
            raise SourceError(f"{plan['name']}: no {plan['armor']} item for {slot} in the current-gear corpus")
        used.add(iid)
        equipment[slot] = _entry(snapshot, pools, iid, enchants=plan.get("enchants", {}).get(slot, ()))
    neck = _pick_inv(pools, prefer, 2, used) or _pick_inv(pools, other, 2, used)
    used.add(neck)
    equipment["NECK"] = _entry(snapshot, pools, neck, extra_bonus=[SOCKET_BONUS_LIST], gems=[plan["gem"]])
    for slot in ("FINGER1", "FINGER2"):
        ring = _pick_inv(pools, prefer, 11, used) or _pick_inv(pools, other, 11, used)
        used.add(ring)
        equipment[slot] = _entry(snapshot, pools, ring)
    if plan.get("trinket1"):
        used.add(plan["trinket1"])
        equipment["TRINKET1"] = _entry(snapshot, pools, plan["trinket1"])
    else:
        tr = _pick_inv(pools, prefer, 12, used) or _pick_inv(pools, other, 12, used)
        used.add(tr)
        equipment["TRINKET1"] = _entry(snapshot, pools, tr)
    tr2 = _pick_inv(pools, prefer, 12, used) or _pick_inv(pools, other, 12, used)
    used.add(tr2)
    equipment["TRINKET2"] = _entry(snapshot, pools, tr2)
    for slot, iid in plan["weapons"].items():
        equipment[slot] = _entry(snapshot, pools, iid, enchants=plan.get("enchants", {}).get(slot, ()))
    fixture = {
        "fixture_version": FIXTURE_VERSION,
        "provenance": {
            "snapshot_build": SNAPSHOT_BUILD, "source_kind": "synthetic", "captured_at": None,
            "generator": "python3 character_prep.py synth-fixtures",
            "notes": [
                "SYNTHETIC: no real character; every id is source-valid for the pinned snapshot",
                f"traits: authored starter build (TraitTreeLoadout {loadout_id}) for spec {plan['spec']} + hero sub-tree",
                *notes,
                "items: docs/research/gearing-corpora/current-gear-corpus.json, ItemSparse.ExpansionID 11 only "
                "(contexts 6 Raid_Mythic / 16 MythicPlus_End_of_Run key 10)",
                f"socket: bonus list {SOCKET_BONUS_LIST} (pure ItemBonus type 6) added to NECK as an explicit identity input",
                f"level {FIXTURE_LEVEL}: every current-season item requires level 90 (ItemScalingConfig.RequiredLevel); base "
                "stats opt into Trinity's gap fill (level-80 cell, Trinity authoring, Retail unresolved)",
                *plan.get("notes", []),
            ],
        },
        "identity": {"race_id": plan["race"], "class_id": plan["class"], "spec_id": plan["spec"], "level": FIXTURE_LEVEL},
        "traits": {"entries": entries, "hero_subtree_id": hero, "loadout_string": None},
        "equipment": equipment,
        "server_inputs": {"base_stats": {"source": "world-db-corpus", "path": "docs/research/world-db-corpora/player-base-stats.json",
                                         "fill_rule": "trinity"}},
        "controlled_units": plan.get("controlled_units", {}),
        "options": {"enable_pvp_talents": bool(plan.get("pvp")), "include_class_skill_lines": True},
        "observations": [],
    }
    if plan.get("pvp"):
        fixture["pvp_traits"] = plan["pvp"]
    if plan.get("learned_spells"):
        fixture["learned_spells"] = list(plan["learned_spells"])
    return fixture


#: no-fill-rule variants: the same source identities without the base-stat fill-rule opt-in.  player_classlevelstats has
#: no level-90 row, so /derived/stats must be unresolved (never interpolated); agent F's differential opts into the fill
#: rule for it by itself (witness of the level-81..90 base-stat gap).
NO_FILL_RULE_VARIANTS = {"arms-warrior-plate-2h": "arms-warrior-plate-2h-no-fill-rule"}


def build_fixtures(compiler: Compiler) -> dict[str, dict[str, Any]]:
    pools = _corpus_pools(compiler.snap)
    out = {plan["name"]: build_fixture(compiler, plan, pools) for plan in FIXTURE_PLAN}
    for base, name in NO_FILL_RULE_VARIANTS.items():
        fx = json.loads(json.dumps(out[base]))
        fx["server_inputs"]["base_stats"].pop("fill_rule", None)
        fx["provenance"]["notes"].append(
            f"NO-FILL-RULE VARIANT of {base}: identical source identities without the base-stat fill-rule opt-in; "
            f"player_classlevelstats has no level-{FIXTURE_LEVEL} row, so /derived/stats must be unresolved (never interpolated)")
        out[name] = fx
    return out


def write_fixtures(compiler: Compiler, out_dir: Path = FIXTURES_DIR) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    fixtures = build_fixtures(compiler)
    # the directory is generated: stale fixtures (renamed plans) would otherwise be compiled into the index
    for stale in sorted(out_dir.glob("*.json")):
        stem = stale.name.removesuffix(".compiled.json").removesuffix(".json")
        if stale.name != "index.json" and stem not in fixtures:
            stale.unlink()
    paths = []
    for name, fixture in fixtures.items():
        Fixture.from_dict(fixture)             # structural validation before writing
        path = out_dir / f"{name}.json"
        path.write_text(canonical_json(fixture), encoding="utf-8")
        paths.append(path)
    return paths


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def cmd_synth_fixtures(args: Any) -> int:
    compiler = Compiler(Snapshot(args.tables) if args.tables else Snapshot())
    for path in write_fixtures(compiler, Path(args.out_dir) if args.out_dir else FIXTURES_DIR):
        print(f"wrote {path}")
    return 0


def cmd_all(args: Any) -> int:
    from . import graph as graph_mod
    from . import inputs as inputs_mod
    from .fixture import schema_document
    CORPORA.mkdir(parents=True, exist_ok=True)
    compiler = Compiler(Snapshot(args.tables) if args.tables else Snapshot())
    written = [CORPORA / "fixture-schema.json"]
    written[0].write_text(canonical_json(schema_document()), encoding="utf-8")
    written += inputs_mod.write_corpora(compiler.snap)
    written.append(graph_mod.write_corpus())
    write_fixtures(compiler)
    index = compile_all(compiler)
    for path in written:
        print(f"wrote {path}")
    print(f"wrote {FIXTURES_DIR / 'index.json'} ({index['provenance']['fixture_count']} fixtures)")
    return 0 if all(e["validation_ok"] for e in index["fixtures"]) else 1


def register(subparsers: Any) -> None:
    s = subparsers.add_parser("synth-fixtures", help="write the synthetic differential fixtures (deterministic)")
    s.add_argument("--out-dir", default=None)
    s.add_argument("--tables", default=None)
    s.set_defaults(func=cmd_synth_fixtures)
    a = subparsers.add_parser("all", help="regenerate every Track-E corpus (schema, inventories, graph, fixtures, compiled)")
    a.add_argument("--tables", default=None)
    a.set_defaults(func=cmd_all)
