#!/usr/bin/env python3
"""Generate ``procs/_trinity_names.py`` from the sibling TrinityCore checkout.

Only *names* are generated.  Every proc semantic in the ``procs`` package is
hand-ported from a named consumer; these tables exist so reports can print
``SPELL_ATTR3_CAN_PROC_FROM_PROCS`` instead of ``(3, 0x04000000)``.

Generated tables:
  SPELL_EFFECT_NAMES   enum SpellEffects        (SharedDefines.h)
  SPELL_ATTR_NAMES     enum SpellAttr0..16      (SharedDefines.h)
  SPELL_FAMILY_NAMES   enum SpellFamilyNames    (SharedDefines.h)
  SPELL_TARGET_NAMES   enum Targets             (SharedDefines.h)

Aura names are reused from ``charstats._aura_names`` (same checkout).

Usage::

    python3 scripts/research/tools/gen_proc_names.py [TC_ROOT]
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

#: tools/ -> research/ -> scripts/ -> wowlab-data/ -> shared parent of the sibling repos.
WORKSPACE_PARENT = Path(__file__).resolve().parents[3].parent
TC_ROOT = Path(sys.argv[1] if len(sys.argv) > 1 else WORKSPACE_PARENT / "TrinityCore")
SHARED = TC_ROOT / "src/server/game/Miscellaneous/SharedDefines.h"
OUT = Path(__file__).resolve().parents[1] / "procs" / "_trinity_names.py"

ENTRY = re.compile(r"^\s*([A-Z][A-Z0-9_]+)\s*=\s*(0x[0-9A-Fa-f]+|\d+)\s*,?")


def enum_block(text: str, header: str) -> list[tuple[str, int]]:
    start = text.index(header)
    body_start = text.index("{", start)
    body_end = text.index("};", body_start)
    out = []
    for line in text[body_start + 1:body_end].splitlines():
        match = ENTRY.match(line)
        if match:
            out.append((match.group(1), int(match.group(2), 0)))
    return out


def main() -> int:
    text = SHARED.read_text(encoding="utf-8")
    commit = subprocess.run(["git", "-C", str(TC_ROOT), "rev-parse", "HEAD"],
                            capture_output=True, text=True, check=True).stdout.strip()

    effects = enum_block(text, "enum SpellEffects")
    families = enum_block(text, "enum SpellFamilyNames")
    targets = enum_block(text, "enum Targets")
    attrs: dict[int, list[tuple[str, int]]] = {}
    for index in range(17):
        attrs[index] = enum_block(text, f"enum SpellAttr{index} : uint32")

    lines = [
        '"""Trinity enum names, GENERATED by tools/gen_proc_names.py -- do not edit.',
        "",
        f"Source: src/server/game/Miscellaneous/SharedDefines.h at {commit}.",
        "Names only; no proc semantics depend on these tables.",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        f'TRINITY_COMMIT = "{commit}"',
        "",
        "SPELL_EFFECT_NAMES: dict[int, str] = {",
    ]
    lines += [f"    {value}: {name!r}," for name, value in effects if name != "TOTAL_SPELL_EFFECTS"]
    lines += ["}", "", "SPELL_FAMILY_NAMES: dict[int, str] = {"]
    lines += [f"    {value}: {name!r}," for name, value in families]
    lines += ["}", "", "SPELL_TARGET_NAMES: dict[int, str] = {"]
    lines += [f"    {value}: {name!r}," for name, value in targets if name != "TOTAL_SPELL_TARGETS"]
    lines += ["}", "", "#: (attribute word index, bit value) -> name",
              "SPELL_ATTR_NAMES: dict[tuple[int, int], str] = {"]
    for index, entries in attrs.items():
        for name, value in entries:
            lines.append(f"    ({index}, 0x{value:08X}): {name!r},")
    lines += ["}", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}: {len(effects)} effects, {len(families)} families, "
          f"{sum(len(v) for v in attrs.values())} attribute bits")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
