#!/usr/bin/env python3
"""Extract TrinityCore implicit-target vocabulary code verbatim into generated headers.

Same idea as ``tools/tc_pet_probe``: the C++ side of the differential is
Trinity's own text, compiled against minimal stubs (see ``probe.cpp``).

Extracted verbatim (TrinityCore @ 7f3d43b):
  SharedDefines.h   enum Targets (incl. TOTAL_SPELL_TARGETS), enum SpellEffects
                    (incl. TOTAL_SPELL_EFFECTS), enum SpellAttr13
  SpellDefines.h    enum SpellCastTargetFlags
  DBCEnums.h        enum class SpellEffectAttributes + DEFINE_ENUM_FLAG
  SpellInfo.h       enums SpellTargetSelectionCategories, SpellTargetReferenceTypes,
                    SpellTargetObjectTypes, SpellTargetCheckTypes,
                    SpellTargetDirectionTypes, SpellEffectImplicitTargetTypes;
                    class SpellImplicitTargetInfo; SpellEffectInfo::StaticData
  SpellInfo.cpp     GetTargetFlagMask, SpellImplicitTargetInfo::{ctor, IsArea,
                    GetSelectionCategory, GetReferenceType, GetObjectType, GetCheckType,
                    GetDirectionType, CalcDirectionAngle, GetTarget,
                    GetExplicitTargetMask}, SpellImplicitTargetInfo::_data,
                    SpellEffectInfo::{GetProvidedTargetMask, GetMissingTargetMask,
                    GetImplicitTargetType, GetUsedTargetObjectType, IsEffect},
                    SpellEffectInfo::_data, SpellInfo::_InitializeExplicitTargetMask

Cut points (stubbed in probe.cpp): SpellInfo / SpellEffectInfo are reduced to the
members those bodies read; ``SpellInfo::GetMaxRange`` returns the driver-supplied
``RangeEntry->RangeMax[positive]`` (the no-caster branch of SpellInfo.cpp:3949);
``rand_norm`` returns a driver-supplied value.
"""

from __future__ import annotations

import sys
from pathlib import Path

WORKSPACE_PARENT = Path(__file__).resolve().parents[5]
TC_ROOT = Path(sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] else WORKSPACE_PARENT / "TrinityCore")
OUT_DIR = Path(sys.argv[2] if len(sys.argv) > 2 else Path(__file__).parent)
OUT_DECLS = OUT_DIR / "tc_selector_decls.inc"
OUT_BODIES = OUT_DIR / "tc_selector_bodies.inc"
G = TC_ROOT / "src/server/game"


def read(rel: str) -> str:
    return (G / rel).read_text(encoding="utf-8")


def line_of(text: str, pos: int) -> int:
    return text.count("\n", 0, pos) + 1


def braced(text: str, start: int) -> tuple[int, int]:
    open_brace = text.index("{", start)
    depth = 0
    for pos in range(open_brace, len(text)):
        if text[pos] == "{":
            depth += 1
        elif text[pos] == "}":
            depth -= 1
            if depth == 0:
                return open_brace, pos + 1
    raise SystemExit("unbalanced braces")


def unique(text: str, needle: str, source: str) -> int:
    start = text.find(needle)
    if start < 0:
        raise SystemExit(f"not found in {source}: {needle}")
    if text.find(needle, start + 1) >= 0:
        raise SystemExit(f"not unique in {source}: {needle}")
    return start


def block(text: str, header: str, source: str) -> str:
    """``header { ... };`` (enum / class / struct / static table definition)."""
    start = unique(text, header, source)
    _, end = braced(text, start)
    tail = text[end:end + 3]
    body = text[start:end]
    if tail.startswith(" };"):  # std::array<...> _data = { { ... } };
        body += " };"
    else:
        body += ";"
    return f"// {source}:{line_of(text, start)}\n{body}\n"


def function(text: str, signature: str, source: str) -> str:
    start = unique(text, signature, source)
    _, b = braced(text, start)
    return f"// {source}:{line_of(text, start)}\n{text[start:b]}\n"


def table(text: str, header: str, source: str) -> str:
    start = unique(text, header, source)
    end = text.index("} };", start) + len("} };")
    return f"// {source}:{line_of(text, start)}\n{text[start:end]}\n"


def main() -> int:
    shared = read("Miscellaneous/SharedDefines.h")
    spelldefs = read("Spells/SpellDefines.h")
    dbc = read("DataStores/DBCEnums.h")
    info_h = read("Spells/SpellInfo.h")
    info = read("Spells/SpellInfo.cpp")

    decls = [
        "// GENERATED by tools/tc_target_selector_probe/extract.py from TrinityCore -- do not edit",
        block(shared, "\nenum Targets\n", "SharedDefines.h"),
        block(shared, "\nenum SpellEffects\n", "SharedDefines.h"),
        block(shared, "enum SpellAttr13 : uint32", "SharedDefines.h"),
        block(spelldefs, "enum SpellCastTargetFlags : uint32", "SpellDefines.h"),
        block(dbc, "enum class SpellEffectAttributes\n", "DBCEnums.h"),
        "DEFINE_ENUM_FLAG(SpellEffectAttributes);",
    ]
    for header in ("enum SpellTargetSelectionCategories\n", "enum SpellTargetReferenceTypes\n",
                   "enum SpellTargetObjectTypes : uint8", "enum SpellTargetCheckTypes : uint8",
                   "enum SpellTargetDirectionTypes\n", "enum SpellEffectImplicitTargetTypes\n"):
        decls.append(block(info_h, header, "SpellInfo.h"))
    decls.append(block(info_h, "class TC_GAME_API SpellImplicitTargetInfo\n", "SpellInfo.h"))
    # SpellEffectInfo::StaticData (nested) -- emitted as a free struct the stub class aliases
    sd = unique(info_h, "        StaticData(SpellEffectImplicitTargetTypes implicitTargetType", "SpellInfo.h")
    sd_start = info_h.rindex("struct StaticData", 0, sd)
    _, sd_end = braced(info_h, sd_start)
    decls.append(f"// SpellInfo.h:{line_of(info_h, sd_start)} (SpellEffectInfo::StaticData)\n"
                 + info_h[sd_start:sd_end].replace("struct StaticData", "struct SpellEffectStaticData", 1)
                 .replace("StaticData(SpellEffectImplicitTargetTypes", "SpellEffectStaticData(SpellEffectImplicitTargetTypes", 1)
                 + ";\n")

    bodies = [
        "// GENERATED by tools/tc_target_selector_probe/extract.py from TrinityCore -- do not edit",
        function(info, "uint32 GetTargetFlagMask(SpellTargetObjectTypes objType)", "SpellInfo.cpp"),
        function(info, "SpellImplicitTargetInfo::SpellImplicitTargetInfo(uint32 target)", "SpellInfo.cpp"),
    ]
    for sig in ("bool SpellImplicitTargetInfo::IsArea() const",
                "SpellTargetSelectionCategories SpellImplicitTargetInfo::GetSelectionCategory() const",
                "SpellTargetReferenceTypes SpellImplicitTargetInfo::GetReferenceType() const",
                "SpellTargetObjectTypes SpellImplicitTargetInfo::GetObjectType() const",
                "SpellTargetCheckTypes SpellImplicitTargetInfo::GetCheckType() const",
                "SpellTargetDirectionTypes SpellImplicitTargetInfo::GetDirectionType() const",
                "float SpellImplicitTargetInfo::CalcDirectionAngle() const",
                "Targets SpellImplicitTargetInfo::GetTarget() const",
                "uint32 SpellImplicitTargetInfo::GetExplicitTargetMask(bool& srcSet, bool& dstSet) const",
                "bool SpellEffectInfo::IsEffect() const",
                "uint32 SpellEffectInfo::GetProvidedTargetMask() const",
                "uint32 SpellEffectInfo::GetMissingTargetMask(bool srcSet /*= false*/, bool dstSet /*= false*/, uint32 mask /*=0*/) const",
                "SpellEffectImplicitTargetTypes SpellEffectInfo::GetImplicitTargetType() const",
                "SpellTargetObjectTypes SpellEffectInfo::GetUsedTargetObjectType() const",
                "void SpellInfo::_InitializeExplicitTargetMask()"):
        bodies.append(function(info, sig, "SpellInfo.cpp"))
    bodies.append(table(info, "std::array<SpellImplicitTargetInfo::StaticData, TOTAL_SPELL_TARGETS> SpellImplicitTargetInfo::_data =", "SpellInfo.cpp"))
    bodies.append(table(info, "std::array<SpellEffectInfo::StaticData, TOTAL_SPELL_EFFECTS> SpellEffectInfo::_data =", "SpellInfo.cpp"))

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_DECLS.write_text("\n\n".join(decls) + "\n", encoding="utf-8")
    OUT_BODIES.write_text("\n\n".join(bodies) + "\n", encoding="utf-8")
    print(f"wrote {OUT_DECLS.name} ({len(decls)} blocks), {OUT_BODIES.name} ({len(bodies)} blocks) from {TC_ROOT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
