#!/usr/bin/env python3
"""Extract TrinityCore position / distance / area-check code verbatim.

Same idea as ``tools/tc_pet_probe``: the C++ side of the targeting geometry
differential (``targeting/geometry.py``, ``targeting/area.py``) is Trinity's own
text, compiled against minimal stubs (see ``probe.cpp``).

Included directly (not extracted): ``Entities/Object/Position.h`` (the inline
distance / angle members), ``G3D/g3dmath.h`` (fuzzyEq/fuzzyGe).

Extracted verbatim (TrinityCore @ 7f3d43b):
  Position.cpp  Position::operator==, IsWithinBox, IsWithinVerticalCylinder,
                HasInArc, HasInLine, NormalizeOrientation
  Util.cpp      DegToRad
  Object.cpp    WorldObject::_IsWithinDist, GetDistance (x3), GetDistance2d (x2),
                IsWithinDist3d (x2), IsWithinDist2d (x2), IsWithinDist, GetDistanceOrder,
                IsInRange, IsInRange2d, IsInRange3d, IsInBetween
  Object.h      Trinity::ObjectDistanceOrderPred
  Unit.cpp      Unit::IsWithinBoundaryRadius
  ObjectDefines.h / Spell.h  #define MIN_MELEE_REACH, EXTRA_CELL_SEARCH_RADIUS, TRAJECTORY_MISSILE_SIZE
  Spell.h       namespace Trinity check declarations (WorldObjectSpell*TargetCheck)
  Spell.cpp     WorldObjectSpell{Nearby,Area,Cone,Traj,Line}TargetCheck ctors + operator()

Cut points (stubbed in probe.cpp): WorldObjectSpellTargetCheck ctor/dtor/operator()
(relation, CheckTarget, conditions: driver-supplied per-target boolean),
GameObject::IsInRange (probe candidates are units only), map/phase membership
(always same map / phase), transports (none), SpellInfo::HasAttribute (driver flags).
"""

from __future__ import annotations

import sys
from pathlib import Path

WORKSPACE_PARENT = Path(__file__).resolve().parents[5]
TC_ROOT = Path(sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] else WORKSPACE_PARENT / "TrinityCore")
OUT_DIR = Path(sys.argv[2] if len(sys.argv) > 2 else Path(__file__).parent)
OUT_DECLS = OUT_DIR / "tc_geom_decls.inc"
OUT_BODIES = OUT_DIR / "tc_geom_bodies.inc"
G = TC_ROOT / "src/server/game"


def braced(text: str, start: int) -> tuple[int, int]:
    open_brace = text.index("{", start)
    depth = 0
    for pos in range(open_brace, len(text)):
        if text[pos] == "{":
            depth += 1
        elif text[pos] == "}":
            depth -= 1
            if depth == 0:
                return open_brace, pos + 1
    raise SystemExit("unbalanced braces")


def function(text: str, signature: str, source: str) -> str:
    start = text.find(signature)
    if start < 0:
        raise SystemExit(f"signature not found in {source}: {signature}")
    if text.find(signature, start + 1) >= 0:
        raise SystemExit(f"signature not unique in {source}: {signature}")
    line = text.count("\n", 0, start) + 1
    _, b = braced(text, start)
    return f"// {source}:{line}\n{text[start:b]}\n"


def between(text: str, first: str, last: str, source: str) -> str:
    a = text.index(first)
    b = text.index(last, a)
    line = text.count("\n", 0, a) + 1
    return f"// {source}:{line}\n{text[a:b]}"


def define(text: str, name: str, source: str) -> str:
    for n, line in enumerate(text.splitlines(), 1):
        if line.startswith(f"#define {name} "):
            return f"// {source}:{n}\n{line}"
    raise SystemExit(f"#define {name} not found in {source}")


def main() -> int:
    pos_cpp = (G / "Entities/Object/Position.cpp").read_text(encoding="utf-8")
    obj_cpp = (G / "Entities/Object/Object.cpp").read_text(encoding="utf-8")
    obj_h = (G / "Entities/Object/Object.h").read_text(encoding="utf-8")
    unit_cpp = (G / "Entities/Unit/Unit.cpp").read_text(encoding="utf-8")
    spell_h = (G / "Spells/Spell.h").read_text(encoding="utf-8")
    spell_cpp = (G / "Spells/Spell.cpp").read_text(encoding="utf-8")
    util_cpp = (TC_ROOT / "src/common/Utilities/Util.cpp").read_text(encoding="utf-8")

    obj_defs = (G / "Entities/Object/ObjectDefines.h").read_text(encoding="utf-8")
    decls = [
        "// GENERATED by tools/tc_target_geom_probe/extract.py from TrinityCore -- do not edit",
        define(obj_defs, "MIN_MELEE_REACH", "ObjectDefines.h"),
        define(obj_defs, "EXTRA_CELL_SEARCH_RADIUS", "ObjectDefines.h"),
        define(spell_h, "TRAJECTORY_MISSILE_SIZE", "Spell.h"),
        between(spell_h, "namespace Trinity\n{\n    struct TC_GAME_API WorldObjectSpellTargetCheck",
                "    TC_GAME_API void SelectRandomInjuredTargets", "Spell.h") + "}\n",
        between(obj_h, "namespace Trinity\n{\n    // Binary predicate to sort WorldObjects", "#endif", "Object.h"),
    ]
    bodies = ["// GENERATED by tools/tc_target_geom_probe/extract.py from TrinityCore -- do not edit"]
    for sig in ("bool Position::operator==(Position const& a) const",
                "bool Position::IsWithinBox(Position const& boxOrigin, float length, float width, float height) const",
                "bool Position::IsWithinVerticalCylinder(Position const& cylinderOrigin, float radius, float height, bool isDoubleVertical) const",
                "bool Position::HasInArc(float arc, Position const* obj, float border) const",
                "bool Position::HasInLine(Position const* pos, float objSize, float width) const",
                "float Position::NormalizeOrientation(float o)"):
        bodies.append(function(pos_cpp, sig, "Position.cpp"))
    bodies.append(function(util_cpp, "float DegToRad(float degrees)", "Util.cpp"))
    for sig in ("bool WorldObject::_IsWithinDist(WorldObject const* obj, float dist2compare, bool is3D, bool incOwnRadius, bool incTargetRadius) const",
                "float WorldObject::GetDistance(WorldObject const* obj) const",
                "float WorldObject::GetDistance(Position const& pos) const",
                "float WorldObject::GetDistance(float x, float y, float z) const",
                "float WorldObject::GetDistance2d(WorldObject const* obj) const",
                "float WorldObject::GetDistance2d(float x, float y) const",
                "bool WorldObject::IsWithinDist3d(float x, float y, float z, float dist) const",
                "bool WorldObject::IsWithinDist3d(Position const* pos, float dist) const",
                "bool WorldObject::IsWithinDist2d(float x, float y, float dist) const",
                "bool WorldObject::IsWithinDist2d(Position const* pos, float dist) const",
                "bool WorldObject::IsWithinDist(WorldObject const* obj, float dist2compare, bool is3D /*= true*/, bool incOwnRadius /*= true*/, bool incTargetRadius /*= true*/) const",
                "bool WorldObject::GetDistanceOrder(WorldObject const* obj1, WorldObject const* obj2, bool is3D /* = true */) const",
                "bool WorldObject::IsInRange(WorldObject const* obj, float minRange, float maxRange, bool is3D /* = true */) const",
                "bool WorldObject::IsInRange2d(Position const* pos, float minRange, float maxRange) const",
                "bool WorldObject::IsInRange3d(Position const* pos, float minRange, float maxRange) const",
                "bool WorldObject::IsInBetween(Position const& pos1, Position const& pos2, float size) const"):
        bodies.append(function(obj_cpp, sig, "Object.cpp"))
    bodies.append(function(unit_cpp, "bool Unit::IsWithinBoundaryRadius(const Unit* obj) const", "Unit.cpp"))
    bodies.append("namespace Trinity\n{")
    for sig in ("WorldObjectSpellNearbyTargetCheck::WorldObjectSpellNearbyTargetCheck(",
                "bool WorldObjectSpellNearbyTargetCheck::operator()(WorldObject* target)",
                "WorldObjectSpellAreaTargetCheck::WorldObjectSpellAreaTargetCheck(",
                "bool WorldObjectSpellAreaTargetCheck::operator()(WorldObject* target) const",
                "WorldObjectSpellConeTargetCheck::WorldObjectSpellConeTargetCheck(",
                "bool WorldObjectSpellConeTargetCheck::operator()(WorldObject* target) const",
                "WorldObjectSpellTrajTargetCheck::WorldObjectSpellTrajTargetCheck(",
                "bool WorldObjectSpellTrajTargetCheck::operator()(WorldObject* target) const",
                "WorldObjectSpellLineTargetCheck::WorldObjectSpellLineTargetCheck(",
                "bool WorldObjectSpellLineTargetCheck::operator()(WorldObject* target) const"):
        bodies.append(function(spell_cpp, sig, "Spell.cpp"))
    bodies.append("}")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT_DECLS.write_text("\n\n".join(decls) + "\n", encoding="utf-8")
    OUT_BODIES.write_text("\n\n".join(bodies) + "\n", encoding="utf-8")
    print(f"wrote {OUT_DECLS.name} ({len(decls)} blocks), {OUT_BODIES.name} ({len(bodies)} blocks) from {TC_ROOT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
