#!/usr/bin/env python3
"""Extract TrinityCore area-aura lifecycle code verbatim (aura-lifecycle Track F).

The C++ side of the differential for ``aura_lifecycle/recipients.py``: Trinity's own text of the
owner-update loop, compiled against minimal stubs (``probe.cpp``).

Extracted verbatim (TrinityCore @ 7f3d43b):
  SpellAuras.cpp       Aura::UpdateOwner, Aura::Update, Aura::UpdateTargetMap, Aura::_Remove
  SpellAuraEffects.cpp AuraEffect::Update, AuraEffect::ResetPeriodic, AuraEffect::GetTotalTicks,
                       AuraEffect::GetApplicationList (template)
  Unit.cpp             Unit::RemoveOwnedAura(AuraMap::iterator&, AuraRemoveMode) and the two aura loops of
                       Unit::_UpdateSpells (owner updates, then expired removal)
  SpellAuras.h         UPDATE_TARGET_MAP_INTERVAL
"""

from __future__ import annotations

import sys
from pathlib import Path

WORKSPACE_PARENT = Path(__file__).resolve().parents[5]
TC_ROOT = Path(sys.argv[1] if len(sys.argv) > 1 and sys.argv[1] else WORKSPACE_PARENT / "TrinityCore")
OUT_DIR = Path(sys.argv[2] if len(sys.argv) > 2 else Path(__file__).parent)
OUT = OUT_DIR / "tc_area_bodies.inc"
G = TC_ROOT / "src/server/game"


def braced(text: str, start: int) -> tuple[int, int]:
    open_brace = text.index("{", start)
    depth = 0
    for pos in range(open_brace, len(text)):
        if text[pos] == "{":
            depth += 1
        elif text[pos] == "}":
            depth -= 1
            if depth == 0:
                return open_brace, pos + 1
    raise SystemExit("unbalanced braces")


def function(text: str, signature: str, source: str, prefix: str = "") -> str:
    start = text.find(signature)
    if start < 0:
        raise SystemExit(f"signature not found in {source}: {signature}")
    if text.find(signature, start + 1) >= 0:
        raise SystemExit(f"signature not unique in {source}: {signature}")
    line = text.count("\n", 0, start) + 1
    _, b = braced(text, start)
    return f"// {source}:{line}\n{prefix}{text[start:b]}\n"


def statement(text: str, first: str, last: str, source: str) -> str:
    a = text.index(first)
    b = text.index(last, a)
    line = text.count("\n", 0, a) + 1
    return f"// {source}:{line}\n{text[a:b]}"


def define(text: str, name: str, source: str) -> str:
    for n, line in enumerate(text.splitlines(), 1):
        if line.startswith(f"#define {name} "):
            return f"// {source}:{n}\n{line}"
    raise SystemExit(f"#define {name} not found in {source}")


def main() -> int:
    auras_cpp = (G / "Spells/Auras/SpellAuras.cpp").read_text(encoding="utf-8")
    auras_h = (G / "Spells/Auras/SpellAuras.h").read_text(encoding="utf-8")
    eff_cpp = (G / "Spells/Auras/SpellAuraEffects.cpp").read_text(encoding="utf-8")
    unit_cpp = (G / "Entities/Unit/Unit.cpp").read_text(encoding="utf-8")

    out = ["// GENERATED by tools/tc_aura_area_probe/extract.py from TrinityCore -- do not edit",
           define(auras_h, "UPDATE_TARGET_MAP_INTERVAL", "SpellAuras.h")]
    for sig in ("void Aura::UpdateOwner(uint32 diff, WorldObject* owner)",
                "void Aura::Update(uint32 diff, Unit* caster)",
                "void Aura::UpdateTargetMap(Unit* caster, bool apply)",
                "void Aura::_Remove(AuraRemoveMode removeMode)"):
        out.append(function(auras_cpp, sig, "SpellAuras.cpp"))
    out.append(function(eff_cpp, "void AuraEffect::GetApplicationList(Container& applicationContainer) const",
                        "SpellAuraEffects.cpp", prefix="template <typename Container>\n"))
    for sig in ("uint32 AuraEffect::GetTotalTicks() const",
                "void AuraEffect::ResetPeriodic(bool resetPeriodicTimer /*= false*/)",
                "void AuraEffect::Update(uint32 diff, Unit* caster)"):
        out.append(function(eff_cpp, sig, "SpellAuraEffects.cpp"))
    out.append(function(unit_cpp, "void Unit::RemoveOwnedAura(AuraMap::iterator& i, AuraRemoveMode removeMode)", "Unit.cpp"))
    loops = statement(unit_cpp, "    // m_auraUpdateIterator can be updated in indirect called code",
                      "    for (AuraApplication* visibleAura : m_visibleAurasToUpdate)", "Unit.cpp")
    out.append("void Unit::UpdateSpellsAuraLoops(uint32 time)\n{\n" + loops + "}\n")

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    OUT.write_text("\n\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {OUT.name} ({len(out)} blocks) from {TC_ROOT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
